export const languages = {
  en: { name: 'English', flag: '🇬🇧' },
  ru: { name: 'Русский', flag: '🇷🇺' },
  ko: { name: '한국어', flag: '🇰🇷' },
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  ja: { name: '日本語', flag: '🇯🇵' },
} as const

export type Language = keyof typeof languages

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'how-it-works': 'How it works',
    benefits: 'Benefits',
    partners: 'Partners',
    faq: 'FAQ',
    dashboard: 'Dashboard',
    login: 'Login',
    signup: 'Sign up',
    logout: 'Logout',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    start: 'Get started',
    open_menu: 'Open menu',
    close_menu: 'Close menu',
    back: 'Dashboard',
    'qr-and-points': 'QR & Points',
    welcome: 'Welcome!',
    'track-progress': 'Track your progress and earn rewards',
    'recent-activity': 'Recent Activity',
    'available-rewards': 'Available Rewards',
    'all-rewards': 'All Rewards',
    'find-dropoff': 'Find a Drop-off Point',
    'dropoff-count': 'Over 500 locations in your city',
    'open-map': 'Open Map',
    'rewards-catalog': 'Rewards Catalog',
    'your-balance': 'Your balance',
    'get-reward': 'Redeem',
    'not-enough-points': 'Not enough',
    'points-needed': 'more points needed',
    'redeem-soon': 'Redemption coming soon',
    'open-cabinet': 'Open Dashboard →',
    'qr-and-balance': 'QR code & balance →',
    'your-ecopoints-card': 'Your EcoPoints Card',
    'show-code': 'Show the code at a drop-off point or share an invite',
    balance: 'Balance',
    'points-available': 'points available',
    'member-card': 'Member Card',
    'member-card-desc': 'Scan at the drop-off point to identify your EcoPoints account.',
    'invite-friend': 'Invite a Friend',
    'invite-friend-desc': 'A friend follows the link and signs up — bonuses are credited per program rules.',
    'invite-code': 'Invite code',
    'cat-all': 'All',
    'cat-grocery': 'Grocery',
    'cat-cafe': 'Café',
    'cat-online': 'Online',
    'cat-sport': 'Sport',
    'cat-transport': 'Transport',
    'points-label': 'Points',
    'kg-recycled': 'Recycled kg',
    'rewards-count': 'Rewards',
    'act-plastic': 'Recycled 5 kg of plastic',
    'act-discount-cafe': '15% off at Kofemainia',
    'act-paper': 'Recycled 3 kg of paper',
    'act-bonus': 'Activity bonus',
    'time-2h': '2 hours ago',
    'time-yesterday': 'Yesterday',
    'time-3d': '3 days ago',
    'time-week': 'A week ago',
    'reward-perekrestok': '10% off at Perekrestok',
    'reward-starbucks': 'Free coffee at Starbucks',
    'reward-ozon': '20% off on Ozon',
    'points-word': 'pts',
    'reward-perekrestok': '10% off at Perekrestok',
    'reward-perekrestok-desc': 'Any purchase from 500 ₽',
    'reward-starbucks': 'Free coffee at Starbucks',
    'reward-starbucks-desc': 'Any drink up to 500 ml',
    'reward-ozon': '20% off on Ozon',
    'reward-ozon-desc': 'Order from 1000 ₽',
    'reward-kofemainia': '15% off at Kofemainia',
    'reward-kofemainia-desc': 'All menu except alcohol',
    'reward-worldclass': '1-day pass at World Class',
    'reward-worldclass-desc': 'Access to all club zones',
    'reward-vkusvill': '10% off at VkusVill',
    'reward-vkusvill-desc': 'Full assortment',
    'reward-yandex': 'Yandex Go ride',
    'reward-yandex-desc': 'Promo code for 150 ₽',
    'reward-lamoda': '25% off at Lamoda',
    'reward-lamoda-desc': 'First order',
    'reward-fitnesshouse': 'Free workout at Fitness House',
    'reward-fitnesshouse-desc': 'Single visit',
    'reward-magnit': '10% off at Magnit',
    'reward-magnit-desc': 'Purchase from 300 ₽',
    'reward-costa': 'Free coffee at Costa Coffee',
    'reward-costa-desc': 'Any drink size M',
    'reward-scooter': 'Scooter — 30 min free',
    'reward-scooter-desc': 'Ride promo code',
  },
  ru: {
    'how-it-works': 'Как это работает',
    benefits: 'Преимущества',
    partners: 'Партнёрам',
    faq: 'FAQ',
    dashboard: 'Кабинет',
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    theme: 'Тема',
    language: 'Язык',
    light: 'Светлая',
    dark: 'Тёмная',
    system: 'Система',
    start: 'Начать',
    open_menu: 'Открыть меню',
    close_menu: 'Закрыть меню',
    back: 'Личный кабинет',
    'qr-and-points': 'QR и баллы',
    welcome: 'Добро пожаловать!',
    'track-progress': 'Отслеживайте свой прогресс и получайте награды',
    'recent-activity': 'Последняя активность',
    'available-rewards': 'Доступные награды',
    'all-rewards': 'Все награды',
    'find-dropoff': 'Найти пункт приёма',
    'dropoff-count': 'Более 500 точек в вашем городе',
    'open-map': 'Открыть карту',
    'rewards-catalog': 'Каталог наград',
    'your-balance': 'Ваш баланс',
    'get-reward': 'Получить',
    'not-enough-points': 'Мало баллов',
    'points-needed': 'баллов не хватает',
    'redeem-soon': 'Обмен наград скоро появится',
    'open-cabinet': 'Открыть кабинет →',
    'qr-and-balance': 'QR-код и баланс →',
    'your-ecopoints-card': 'Ваша карта EcoPoints',
    'show-code': 'Покажите код на пункте приёма или поделитесь приглашением',
    balance: 'Баланс',
    'points-available': 'баллов доступно',
    'member-card': 'Карта участника',
    'member-card-desc': 'Сканируйте на пункте приёма для идентификации вашего аккаунта EcoPoints.',
    'invite-friend': 'Пригласить друга',
    'invite-friend-desc': 'Друг переходит по ссылке из кода и регистрируется — бонусы начисляются по правилам программы.',
    'invite-code': 'Код приглашения',
    'cat-all': 'Все',
    'cat-grocery': 'Продукты',
    'cat-cafe': 'Кафе',
    'cat-online': 'Онлайн',
    'cat-sport': 'Спорт',
    'cat-transport': 'Транспорт',
    'points-label': 'Баллы',
    'kg-recycled': 'Сдано кг',
    'rewards-count': 'Награды',
    'act-plastic': 'Сдано 5 кг пластика',
    'act-discount-cafe': 'Скидка 15% в Кофемании',
    'act-paper': 'Сдано 3 кг макулатуры',
    'act-bonus': 'Бонус за активность',
    'time-2h': '2 часа назад',
    'time-yesterday': 'Вчера',
    'time-3d': '3 дня назад',
    'time-week': 'Неделю назад',
    'reward-perekrestok': 'Скидка 10% в Перекрёстке',
    'reward-starbucks': 'Бесплатный кофе в Starbucks',
    'reward-ozon': 'Скидка 20% на Ozon',
    'points-word': 'баллов',
    'reward-perekrestok': 'Скидка 10% в Перекрёстке',
    'reward-perekrestok-desc': 'На любую покупку от 500 ₽',
    'reward-starbucks': 'Бесплатный кофе в Starbucks',
    'reward-starbucks-desc': 'Любой напиток до 500 мл',
    'reward-ozon': 'Скидка 20% на Ozon',
    'reward-ozon-desc': 'На заказ от 1000 ₽',
    'reward-kofemainia': 'Скидка 15% в Кофемании',
    'reward-kofemainia-desc': 'На все меню, кроме алкоголя',
    'reward-worldclass': 'Абонемент на 1 день в World Class',
    'reward-worldclass-desc': 'Доступ ко всем зонам клуба',
    'reward-vkusvill': 'Скидка 10% в ВкусВилл',
    'reward-vkusvill-desc': 'На весь ассортимент',
    'reward-yandex': 'Поездка на Яндекс Go',
    'reward-yandex-desc': 'Промокод на 150 ₽',
    'reward-lamoda': 'Скидка 25% в Lamoda',
    'reward-lamoda-desc': 'На первый заказ',
    'reward-fitnesshouse': 'Бесплатная тренировка в Фитнес Хаус',
    'reward-fitnesshouse-desc': 'Разовое посещение',
    'reward-magnit': 'Скидка 10% в Магните',
    'reward-magnit-desc': 'На покупку от 300 ₽',
    'reward-costa': 'Кофе в подарок в Costa Coffee',
    'reward-costa-desc': 'Любой напиток размера М',
    'reward-scooter': 'Самокат — 30 минут бесплатно',
    'reward-scooter-desc': 'Промокод на поездку',
  },
  ko: {
    'how-it-works': '작동 원리',
    benefits: '이점',
    partners: '파트너',
    faq: '자주 묻는 질문',
    dashboard: '대시보드',
    login: '로그인',
    signup: '가입',
    logout: '로그아웃',
    theme: '테마',
    language: '언어',
    light: '밝음',
    dark: '어두움',
    system: '시스템',
    start: '시작하기',
    open_menu: '메뉴 열기',
    close_menu: '메뉴 닫기',
    back: '대시보드',
    'qr-and-points': 'QR 및 포인트',
    welcome: '환영합니다!',
    'track-progress': '진행 상황을 추적하고 보상을 받으세요',
    'recent-activity': '최근 활동',
    'available-rewards': '사용 가능한 보상',
    'all-rewards': '모든 보상',
    'find-dropoff': '수거 지점 찾기',
    'dropoff-count': '도시 내 500개 이상 지점',
    'open-map': '지도 열기',
    'rewards-catalog': '보상 카탈로그',
    'your-balance': '잔액',
    'get-reward': '받기',
    'not-enough-points': '포인트 부족',
    'points-needed': '포인트 더 필요',
    'redeem-soon': '곧 교환 가능',
    'open-cabinet': '대시보드 열기 →',
    'qr-and-balance': 'QR 코드 및 잔액 →',
    'your-ecopoints-card': 'EcoPoints 카드',
    'show-code': '수거 지점에서 코드를 보여주거나 초대장을 공유하세요',
    balance: '잔액',
    'points-available': '포인트 사용 가능',
    'member-card': '회원 카드',
    'member-card-desc': '수거 지점에서 스캔하여 EcoPoints 계정을 확인하세요.',
    'invite-friend': '친구 초대',
    'invite-friend-desc': '친구가 링크를 통해 가입하면 프로그램 규정에 따라 보너스가 지급됩니다.',
    'invite-code': '초대 코드',
    'cat-all': '전체',
    'cat-grocery': '식료품',
    'cat-cafe': '카페',
    'cat-online': '온라인',
    'cat-sport': '스포츠',
    'cat-transport': '교통',
    'points-label': '포인트',
    'kg-recycled': '재활용 kg',
    'rewards-count': '보상',
    'act-plastic': '플라스틱 5kg 재활용',
    'act-discount-cafe': 'Kofemainia 15% 할인',
    'act-paper': '종이 3kg 재활용',
    'act-bonus': '활동 보너스',
    'time-2h': '2시간 전',
    'time-yesterday': '어제',
    'time-3d': '3일 전',
    'time-week': '1주일 전',
    'reward-perekrestok': 'Perekrestok 10% 할인',
    'reward-starbucks': 'Starbucks 무료 커피',
    'reward-ozon': 'Ozon 20% 할인',
    'points-word': '포인트',
    'reward-perekrestok': 'Perekrestok 10% 할인',
    'reward-perekrestok-desc': '500 ₽ 이상 구매 시',
    'reward-starbucks': 'Starbucks 무료 커피',
    'reward-starbucks-desc': '500ml 이하 음료',
    'reward-ozon': 'Ozon 20% 할인',
    'reward-ozon-desc': '1000 ₽ 이상 주문',
    'reward-kofemainia': 'Kofemainia 15% 할인',
    'reward-kofemainia-desc': '주류 제외 전 메뉴',
    'reward-worldclass': 'World Class 1일 이용권',
    'reward-worldclass-desc': '전 구역 이용 가능',
    'reward-vkusvill': 'VkusVill 10% 할인',
    'reward-vkusvill-desc': '전 상품 적용',
    'reward-yandex': 'Yandex Go 탑승',
    'reward-yandex-desc': '150 ₽ 프로모 코드',
    'reward-lamoda': 'Lamoda 25% 할인',
    'reward-lamoda-desc': '첫 주문',
    'reward-fitnesshouse': 'Fitness House 무료 운동',
    'reward-fitnesshouse-desc': '1회 방문',
    'reward-magnit': 'Magnit 10% 할인',
    'reward-magnit-desc': '300 ₽ 이상 구매',
    'reward-costa': 'Costa Coffee 무료 커피',
    'reward-costa-desc': 'M 사이즈 음료',
    'reward-scooter': '전동킥보드 30분 무료',
    'reward-scooter-desc': '탑승 프로모 코드',
  },
  es: {
    'how-it-works': 'Cómo funciona',
    benefits: 'Beneficios',
    partners: 'Socios',
    faq: 'Preguntas frecuentes',
    dashboard: 'Panel de control',
    login: 'Iniciar sesión',
    signup: 'Registrarse',
    logout: 'Cerrar sesión',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    start: 'Comenzar',
    open_menu: 'Abrir menú',
    close_menu: 'Cerrar menú',
    back: 'Panel',
    'qr-and-points': 'QR y Puntos',
    welcome: '¡Bienvenido!',
    'track-progress': 'Sigue tu progreso y obtén recompensas',
    'recent-activity': 'Actividad Reciente',
    'available-rewards': 'Recompensas Disponibles',
    'all-rewards': 'Todas las Recompensas',
    'find-dropoff': 'Encontrar Punto de Entrega',
    'dropoff-count': 'Más de 500 puntos en tu ciudad',
    'open-map': 'Abrir Mapa',
    'rewards-catalog': 'Catálogo de Recompensas',
    'your-balance': 'Tu saldo',
    'get-reward': 'Obtener',
    'not-enough-points': 'Sin puntos',
    'points-needed': 'puntos más necesarios',
    'redeem-soon': 'Canje próximamente',
    'open-cabinet': 'Abrir Panel →',
    'qr-and-balance': 'Código QR y saldo →',
    'your-ecopoints-card': 'Tu Tarjeta EcoPoints',
    'show-code': 'Muestra el código en el punto de entrega o comparte una invitación',
    balance: 'Saldo',
    'points-available': 'puntos disponibles',
    'member-card': 'Tarjeta de Miembro',
    'member-card-desc': 'Escanea en el punto de entrega para identificar tu cuenta EcoPoints.',
    'invite-friend': 'Invitar a un Amigo',
    'invite-friend-desc': 'Un amigo sigue el enlace y se registra — los bonos se acreditan según las reglas del programa.',
    'invite-code': 'Código de invitación',
    'cat-all': 'Todo',
    'cat-grocery': 'Alimentación',
    'cat-cafe': 'Café',
    'cat-online': 'Online',
    'cat-sport': 'Deporte',
    'cat-transport': 'Transporte',
    'points-label': 'Puntos',
    'kg-recycled': 'kg reciclados',
    'rewards-count': 'Recompensas',
    'act-plastic': 'Reciclados 5 kg de plástico',
    'act-discount-cafe': '15% de descuento en Kofemainia',
    'act-paper': 'Reciclados 3 kg de papel',
    'act-bonus': 'Bono de actividad',
    'time-2h': 'Hace 2 horas',
    'time-yesterday': 'Ayer',
    'time-3d': 'Hace 3 días',
    'time-week': 'Hace una semana',
    'reward-perekrestok': '10% de descuento en Perekrestok',
    'reward-starbucks': 'Café gratis en Starbucks',
    'reward-ozon': '20% de descuento en Ozon',
    'points-word': 'pts',
    'reward-perekrestok': '10% de descuento en Perekrestok',
    'reward-perekrestok-desc': 'Compra desde 500 ₽',
    'reward-starbucks': 'Café gratis en Starbucks',
    'reward-starbucks-desc': 'Bebida hasta 500 ml',
    'reward-ozon': '20% de descuento en Ozon',
    'reward-ozon-desc': 'Pedido desde 1000 ₽',
    'reward-kofemainia': '15% de descuento en Kofemainia',
    'reward-kofemainia-desc': 'Todo el menú excepto alcohol',
    'reward-worldclass': 'Pase de 1 día en World Class',
    'reward-worldclass-desc': 'Acceso a todas las zonas',
    'reward-vkusvill': '10% de descuento en VkusVill',
    'reward-vkusvill-desc': 'Todo el surtido',
    'reward-yandex': 'Viaje en Yandex Go',
    'reward-yandex-desc': 'Código promo por 150 ₽',
    'reward-lamoda': '25% de descuento en Lamoda',
    'reward-lamoda-desc': 'Primer pedido',
    'reward-fitnesshouse': 'Entrenamiento gratis en Fitness House',
    'reward-fitnesshouse-desc': 'Una visita',
    'reward-magnit': '10% de descuento en Magnit',
    'reward-magnit-desc': 'Compra desde 300 ₽',
    'reward-costa': 'Café gratis en Costa Coffee',
    'reward-costa-desc': 'Bebida tamaño M',
    'reward-scooter': 'Patinete — 30 min gratis',
    'reward-scooter-desc': 'Código promo de viaje',
  },
  fr: {
    'how-it-works': 'Comment ça marche',
    benefits: 'Avantages',
    partners: 'Partenaires',
    faq: 'FAQ',
    dashboard: 'Tableau de bord',
    login: 'Connexion',
    signup: "S'inscrire",
    logout: 'Déconnexion',
    theme: 'Thème',
    language: 'Langue',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    start: 'Commencer',
    open_menu: 'Ouvrir le menu',
    close_menu: 'Fermer le menu',
    back: 'Tableau de bord',
    'qr-and-points': 'QR et Points',
    welcome: 'Bienvenue !',
    'track-progress': 'Suivez vos progrès et obtenez des récompenses',
    'recent-activity': 'Activité Récente',
    'available-rewards': 'Récompenses Disponibles',
    'all-rewards': 'Toutes les Récompenses',
    'find-dropoff': 'Trouver un Point de Dépôt',
    'dropoff-count': 'Plus de 500 points dans votre ville',
    'open-map': 'Ouvrir la Carte',
    'rewards-catalog': 'Catalogue de Récompenses',
    'your-balance': 'Votre solde',
    'get-reward': 'Obtenir',
    'not-enough-points': 'Pas assez',
    'points-needed': 'points manquants',
    'redeem-soon': 'Échange bientôt disponible',
    'open-cabinet': 'Ouvrir le tableau →',
    'qr-and-balance': 'QR code et solde →',
    'your-ecopoints-card': 'Votre Carte EcoPoints',
    'show-code': 'Montrez le code au point de dépôt ou partagez une invitation',
    balance: 'Solde',
    'points-available': 'points disponibles',
    'member-card': 'Carte Membre',
    'member-card-desc': "Scannez au point de dépôt pour identifier votre compte EcoPoints.",
    'invite-friend': 'Inviter un Ami',
    'invite-friend-desc': "Un ami suit le lien et s'inscrit — les bonus sont crédités selon les règles du programme.",
    'invite-code': "Code d'invitation",
    'cat-all': 'Tout',
    'cat-grocery': 'Alimentation',
    'cat-cafe': 'Café',
    'cat-online': 'En ligne',
    'cat-sport': 'Sport',
    'cat-transport': 'Transport',
    'points-label': 'Points',
    'kg-recycled': 'kg recyclés',
    'rewards-count': 'Récompenses',
    'act-plastic': '5 kg de plastique recyclés',
    'act-discount-cafe': '-15% chez Kofemainia',
    'act-paper': '3 kg de papier recyclés',
    'act-bonus': 'Bonus d\'activité',
    'time-2h': 'Il y a 2 heures',
    'time-yesterday': 'Hier',
    'time-3d': 'Il y a 3 jours',
    'time-week': 'Il y a une semaine',
    'reward-perekrestok': '-10% chez Perekrestok',
    'reward-starbucks': 'Café offert chez Starbucks',
    'reward-ozon': '-20% sur Ozon',
    'points-word': 'pts',
    'reward-perekrestok': '-10% chez Perekrestok',
    'reward-perekrestok-desc': 'Achat à partir de 500 ₽',
    'reward-starbucks': 'Café offert chez Starbucks',
    'reward-starbucks-desc': 'Boisson jusqu\'à 500 ml',
    'reward-ozon': '-20% sur Ozon',
    'reward-ozon-desc': 'Commande à partir de 1000 ₽',
    'reward-kofemainia': '-15% chez Kofemainia',
    'reward-kofemainia-desc': 'Tout le menu sauf alcool',
    'reward-worldclass': 'Pass 1 jour chez World Class',
    'reward-worldclass-desc': 'Accès à toutes les zones',
    'reward-vkusvill': '-10% chez VkusVill',
    'reward-vkusvill-desc': 'Tout l\'assortiment',
    'reward-yandex': 'Trajet Yandex Go',
    'reward-yandex-desc': 'Code promo de 150 ₽',
    'reward-lamoda': '-25% chez Lamoda',
    'reward-lamoda-desc': 'Première commande',
    'reward-fitnesshouse': 'Séance gratuite chez Fitness House',
    'reward-fitnesshouse-desc': 'Visite unique',
    'reward-magnit': '-10% chez Magnit',
    'reward-magnit-desc': 'Achat à partir de 300 ₽',
    'reward-costa': 'Café offert chez Costa Coffee',
    'reward-costa-desc': 'Boisson taille M',
    'reward-scooter': 'Trottinette — 30 min offerts',
    'reward-scooter-desc': 'Code promo de trajet',
  },
  de: {
    'how-it-works': 'So funktioniert es',
    benefits: 'Vorteile',
    partners: 'Partner',
    faq: 'Häufig gestellte Fragen',
    dashboard: 'Dashboard',
    login: 'Anmelden',
    signup: 'Registrieren',
    logout: 'Abmelden',
    theme: 'Design',
    language: 'Sprache',
    light: 'Hell',
    dark: 'Dunkel',
    system: 'System',
    start: 'Loslegen',
    open_menu: 'Menü öffnen',
    close_menu: 'Menü schließen',
    back: 'Dashboard',
    'qr-and-points': 'QR & Punkte',
    welcome: 'Willkommen!',
    'track-progress': 'Verfolgen Sie Ihren Fortschritt und erhalten Sie Prämien',
    'recent-activity': 'Letzte Aktivitäten',
    'available-rewards': 'Verfügbare Prämien',
    'all-rewards': 'Alle Prämien',
    'find-dropoff': 'Abgabepunkt finden',
    'dropoff-count': 'Über 500 Standorte in Ihrer Stadt',
    'open-map': 'Karte öffnen',
    'rewards-catalog': 'Prämien-Katalog',
    'your-balance': 'Ihr Guthaben',
    'get-reward': 'Einlösen',
    'not-enough-points': 'Nicht genug',
    'points-needed': 'Punkte fehlen',
    'redeem-soon': 'Einlösung bald verfügbar',
    'open-cabinet': 'Dashboard öffnen →',
    'qr-and-balance': 'QR-Code & Guthaben →',
    'your-ecopoints-card': 'Ihre EcoPoints-Karte',
    'show-code': 'Zeigen Sie den Code am Abgabepunkt oder teilen Sie eine Einladung',
    balance: 'Guthaben',
    'points-available': 'Punkte verfügbar',
    'member-card': 'Mitgliedskarte',
    'member-card-desc': 'Scannen Sie am Abgabepunkt zur Identifikation Ihres EcoPoints-Kontos.',
    'invite-friend': 'Freund einladen',
    'invite-friend-desc': 'Ein Freund folgt dem Link und registriert sich — Boni werden gemäß den Programmregeln gutgeschrieben.',
    'invite-code': 'Einladungscode',
    'cat-all': 'Alle',
    'cat-grocery': 'Lebensmittel',
    'cat-cafe': 'Café',
    'cat-online': 'Online',
    'cat-sport': 'Sport',
    'cat-transport': 'Transport',
    'points-label': 'Punkte',
    'kg-recycled': 'Recycelte kg',
    'rewards-count': 'Prämien',
    'act-plastic': '5 kg Plastik recycelt',
    'act-discount-cafe': '15% Rabatt bei Kofemainia',
    'act-paper': '3 kg Papier recycelt',
    'act-bonus': 'Aktivitätsbonus',
    'time-2h': 'Vor 2 Stunden',
    'time-yesterday': 'Gestern',
    'time-3d': 'Vor 3 Tagen',
    'time-week': 'Vor einer Woche',
    'reward-perekrestok': '10% Rabatt bei Perekrestok',
    'reward-starbucks': 'Gratis Kaffee bei Starbucks',
    'reward-ozon': '20% Rabatt bei Ozon',
    'points-word': 'Pkt.',
    'reward-perekrestok': '10% Rabatt bei Perekrestok',
    'reward-perekrestok-desc': 'Einkauf ab 500 ₽',
    'reward-starbucks': 'Gratis Kaffee bei Starbucks',
    'reward-starbucks-desc': 'Getränk bis 500 ml',
    'reward-ozon': '20% Rabatt bei Ozon',
    'reward-ozon-desc': 'Bestellung ab 1000 ₽',
    'reward-kofemainia': '15% Rabatt bei Kofemainia',
    'reward-kofemainia-desc': 'Gesamte Karte außer Alkohol',
    'reward-worldclass': '1-Tages-Pass bei World Class',
    'reward-worldclass-desc': 'Zugang zu allen Bereichen',
    'reward-vkusvill': '10% Rabatt bei VkusVill',
    'reward-vkusvill-desc': 'Gesamtes Sortiment',
    'reward-yandex': 'Yandex Go Fahrt',
    'reward-yandex-desc': 'Promo-Code über 150 ₽',
    'reward-lamoda': '25% Rabatt bei Lamoda',
    'reward-lamoda-desc': 'Erste Bestellung',
    'reward-fitnesshouse': 'Gratis Training bei Fitness House',
    'reward-fitnesshouse-desc': 'Einmaliger Besuch',
    'reward-magnit': '10% Rabatt bei Magnit',
    'reward-magnit-desc': 'Einkauf ab 300 ₽',
    'reward-costa': 'Gratis Kaffee bei Costa Coffee',
    'reward-costa-desc': 'Getränk Größe M',
    'reward-scooter': 'Scooter — 30 Min. gratis',
    'reward-scooter-desc': 'Fahrt-Promo-Code',
  },
  ja: {
    'how-it-works': '使い方',
    benefits: 'メリット',
    partners: 'パートナー',
    faq: 'よくある質問',
    dashboard: 'ダッシュボード',
    login: 'ログイン',
    signup: '登録',
    logout: 'ログアウト',
    theme: 'テーマ',
    language: '言語',
    light: 'ライト',
    dark: 'ダーク',
    system: 'システム',
    start: '開始する',
    open_menu: 'メニューを開く',
    close_menu: 'メニューを閉じる',
    back: 'ダッシュボード',
    'qr-and-points': 'QR・ポイント',
    welcome: 'ようこそ！',
    'track-progress': '進捗を追跡して報酬を獲得しましょう',
    'recent-activity': '最近のアクティビティ',
    'available-rewards': '利用可能な報酬',
    'all-rewards': 'すべての報酬',
    'find-dropoff': '回収ポイントを探す',
    'dropoff-count': 'お近くに500か所以上',
    'open-map': '地図を開く',
    'rewards-catalog': '報酬カタログ',
    'your-balance': '残高',
    'get-reward': '獲得する',
    'not-enough-points': 'ポイント不足',
    'points-needed': 'ポイント不足',
    'redeem-soon': '交換機能は近日公開',
    'open-cabinet': 'ダッシュボードを開く →',
    'qr-and-balance': 'QRコード・残高 →',
    'your-ecopoints-card': 'EcoPointsカード',
    'show-code': '回収ポイントでコードを提示するか、招待状を共有してください',
    balance: '残高',
    'points-available': 'ポイント利用可能',
    'member-card': 'メンバーカード',
    'member-card-desc': '回収ポイントでスキャンしてEcoPointsアカウントを確認します。',
    'invite-friend': '友達を招待',
    'invite-friend-desc': '友達がリンクから登録すると、プログラムのルールに従ってボーナスが付与されます。',
    'invite-code': '招待コード',
    'cat-all': 'すべて',
    'cat-grocery': '食料品',
    'cat-cafe': 'カフェ',
    'cat-online': 'オンライン',
    'cat-sport': 'スポーツ',
    'cat-transport': '交通',
    'points-label': 'ポイント',
    'kg-recycled': 'リサイクルkg',
    'rewards-count': '報酬',
    'act-plastic': 'プラスチック5kgをリサイクル',
    'act-discount-cafe': 'Kofemainia 15%割引',
    'act-paper': '紙3kgをリサイクル',
    'act-bonus': 'アクティビティボーナス',
    'time-2h': '2時間前',
    'time-yesterday': '昨日',
    'time-3d': '3日前',
    'time-week': '1週間前',
    'reward-perekrestok': 'Perekrestok 10%割引',
    'reward-starbucks': 'Starbucks 無料コーヒー',
    'reward-ozon': 'Ozon 20%割引',
    'points-word': 'pt',
    'reward-perekrestok': 'Perekrestok 10%割引',
    'reward-perekrestok-desc': '500 ₽以上のお買い物',
    'reward-starbucks': 'Starbucks 無料コーヒー',
    'reward-starbucks-desc': '500ml以下のドリンク',
    'reward-ozon': 'Ozon 20%割引',
    'reward-ozon-desc': '1000 ₽以上の注文',
    'reward-kofemainia': 'Kofemainia 15%割引',
    'reward-kofemainia-desc': 'アルコール以外の全メニュー',
    'reward-worldclass': 'World Class 1日パス',
    'reward-worldclass-desc': '全エリア利用可能',
    'reward-vkusvill': 'VkusVill 10%割引',
    'reward-vkusvill-desc': '全商品対象',
    'reward-yandex': 'Yandex Goライド',
    'reward-yandex-desc': '150 ₽プロモコード',
    'reward-lamoda': 'Lamoda 25%割引',
    'reward-lamoda-desc': '初回注文',
    'reward-fitnesshouse': 'Fitness House 無料トレーニング',
    'reward-fitnesshouse-desc': '1回利用',
    'reward-magnit': 'Magnit 10%割引',
    'reward-magnit-desc': '300 ₽以上のお買い物',
    'reward-costa': 'Costa Coffee 無料コーヒー',
    'reward-costa-desc': 'Mサイズドリンク',
    'reward-scooter': '電動キックボード30分無料',
    'reward-scooter-desc': 'ライドプロモコード',
  },
}

export const getTranslation = (lang: Language, key: string): string => {
  return translations[lang]?.[key] || translations.en[key] || key
}
