export const languages = {
  en: { name: 'English', flag: '🇬🇧' },
  ru: { name: 'Русский', flag: '🇷🇺' },
  ky: { name: 'Кыргызча', flag: '🇰🇬' },
  ko: { name: '한국어', flag: '🇰🇷' },
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  ja: { name: '日本語', flag: '🇯🇵' },
} as const

export type Language = keyof typeof languages

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'how-it-works': 'How it works',
    benefits: 'Benefits',
    partners: 'Partners',
    faq: 'FAQ',
    dashboard: 'Dashboard',
    login: 'Login',
    signup: 'Sign up',
    logout: 'Logout',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    start: 'Get started',
    open_menu: 'Open menu',
    close_menu: 'Close menu',
    back: 'Dashboard',
    'qr-and-points': 'QR & Points',
    welcome: 'Welcome!',
    'track-progress': 'Track your progress and earn rewards',
    'recent-activity': 'Recent Activity',
    'available-rewards': 'Available Rewards',
    'all-rewards': 'All Rewards',
    'find-dropoff': 'Find a Drop-off Point',
    'dropoff-count': 'Over 500 locations in your city',
    'open-map': 'Open Map',
    'rewards-catalog': 'Rewards Catalog',
    'your-balance': 'Your balance',
    'get-reward': 'Redeem',
    'not-enough-points': 'Not enough',
    'points-needed': 'more points needed',
    'redeem-soon': 'Redemption coming soon',
    'open-cabinet': 'Open Dashboard →',
    'qr-and-balance': 'QR code & balance →',
    'your-ecopoints-card': 'Your EcoPoints Card',
    'show-code': 'Show the code at a drop-off point or share an invite',
    balance: 'Balance',
    'points-available': 'points available',
    'member-card': 'Member Card',
    'member-card-desc': 'Scan at the drop-off point to identify your EcoPoints account.',
    'invite-friend': 'Invite a Friend',
    'invite-friend-desc': 'A friend follows the link and signs up — bonuses are credited per program rules.',
    'invite-code': 'Invite code',
    'cat-all': 'All',
    'cat-grocery': 'Grocery',
    'cat-cafe': 'Café',
    'cat-online': 'Online',
    'cat-sport': 'Sport',
    'cat-transport': 'Transport',
    'points-label': 'Points',
    'kg-recycled': 'Recycled kg',
    'rewards-count': 'Rewards',
    'act-plastic': 'Recycled 5 kg of plastic',
    'act-discount-cafe': '15% off at Kofemainia',
    'act-paper': 'Recycled 3 kg of paper',
    'act-bonus': 'Activity bonus',
    'time-2h': '2 hours ago',
    'time-yesterday': 'Yesterday',
    'time-3d': '3 days ago',
    'time-week': 'A week ago',
    'points-word': 'pts',
    'reward-perekrestok': '10% off at Perekrestok',
    'reward-perekrestok-desc': 'Any purchase from 500 ₽',
    'reward-starbucks': 'Free coffee at Starbucks',
    'reward-starbucks-desc': 'Any drink up to 500 ml',
    'reward-ozon': '20% off on Ozon',
    'reward-ozon-desc': 'Order from 1000 ₽',
    'reward-kofemainia': '15% off at Kofemainia',
    'reward-kofemainia-desc': 'All menu except alcohol',
    'reward-worldclass': '1-day pass at World Class',
    'reward-worldclass-desc': 'Access to all club zones',
    'reward-vkusvill': '10% off at VkusVill',
    'reward-vkusvill-desc': 'Full assortment',
    'reward-yandex': 'Yandex Go ride',
    'reward-yandex-desc': 'Promo code for 150 ₽',
    'reward-lamoda': '25% off at Lamoda',
    'reward-lamoda-desc': 'First order',
    'reward-fitnesshouse': 'Free workout at Fitness House',
    'reward-fitnesshouse-desc': 'Single visit',
    'reward-magnit': '10% off at Magnit',
    'reward-magnit-desc': 'Purchase from 300 ₽',
    'reward-costa': 'Free coffee at Costa Coffee',
    'reward-costa-desc': 'Any drink size M',
    'reward-scooter': 'Scooter — 30 min free',
    'reward-scooter-desc': 'Ride promo code',
    'map-title': 'Find Drop-off Points',
    'map-all-types': 'All',
    'map-use-location': 'My Location',
    'map-locating': 'Locating...',
    'map-location-error': 'Location unavailable',
    'map-points-found': 'points found',
    'map-nearest': 'Nearest',
    'map-km': 'km',
    'map-hours': 'Hours',
    'map-pts-per-kg': 'pts/kg',
    'map-route': 'Navigate',
    'map-you-are-here': 'You are here',
    'waste-plastic': 'Plastic',
    'waste-paper': 'Paper',
    'waste-glass': 'Glass',
    'waste-metal': 'Metal',
    'waste-electronics': 'Electronics',
    'waste-organic': 'Organic',
    'hero-badge': 'Ecology + Savings = EcoPoints',
    'hero-h1-1': 'We turn waste',
    'hero-h1-2': 'into value',
    'hero-desc': 'Recycle your waste, earn points and get real discounts from our partners. Caring for the environment is now rewarding.',
    'hero-btn-primary': 'Start earning points',
    'hero-btn-secondary': 'Learn more',
    'hero-stat-dropoff': 'Drop-off points',
    'hero-stat-partners': 'Partners',
    'hero-stat-users': 'Users',
    'hiw-badge': 'Simple process',
    'hiw-title': 'How it works',
    'hiw-desc': 'From registration to real bonuses — just 4 simple steps',
    'hiw-step1-title': 'Register',
    'hiw-step1-desc': 'Create an account in a couple of minutes. It\'s free and takes minimal time.',
    'hiw-step2-title': 'Drop off waste',
    'hiw-step2-desc': 'Find the nearest drop-off point, scan the QR code and hand over your sorted waste.',
    'hiw-step3-title': 'Earn points',
    'hiw-step3-desc': 'The system will automatically credit points depending on the type and weight of waste submitted.',
    'hiw-step4-title': 'Redeem for bonuses',
    'hiw-step4-desc': 'Use accumulated points to get discounts and offers from our partners.',
    'ben-badge': 'Value for everyone',
    'ben-title': 'Platform benefits',
    'ben-desc': 'EcoPoints creates value for users, businesses and the environment',
    'ben-for-users': 'For users',
    'ben-for-biz': 'For business',
    'ben-u1-title': 'Real savings',
    'ben-u1-desc': 'Get discounts and bonuses from hundreds of partners for a simple action — recycling your waste.',
    'ben-u2-title': 'Personal progress',
    'ben-u2-desc': 'Track your environmental contribution: weight of waste recycled, points earned and resources saved.',
    'ben-u3-title': 'Transparent system',
    'ben-u3-desc': 'All operations are recorded. You always know how much you recycled, earned and spent.',
    'ben-b1-title': 'New customers',
    'ben-b1-desc': 'Get access to an audience of eco-conscious users ready to make purchases.',
    'ben-b2-title': 'ESG image',
    'ben-b2-desc': 'Strengthen your reputation as a socially responsible company and meet sustainable development standards.',
    'ben-b3-title': 'Effective marketing',
    'ben-b3-desc': 'Attract customers cheaper than through traditional advertising, with high conversion.',
    'par-badge': 'For business',
    'par-h1': 'Become a',
    'par-h2': 'partner',
    'par-desc': 'Attract eco-conscious customers who are already motivated to buy. Our platform connects your business with an audience that values sustainable development.',
    'par-feat1': 'Access to an active user base',
    'par-feat2': 'Flexible partnership terms',
    'par-feat3': 'Analytics and reporting',
    'par-btn': 'Become a partner',
    'par-cat-1': 'Cafés & restaurants',
    'par-cat-2': 'Supermarkets',
    'par-cat-3': 'Fitness clubs',
    'par-cat-4': 'Online stores',
    'par-cat-5': 'Cinemas',
    'par-cat-6': 'Pharmacies',
    'faq-badge': 'Support',
    'faq-title': 'Frequently asked questions',
    'faq-desc': 'Answers to popular questions about the platform',
    'faq-q1': 'How are points credited?',
    'faq-a1': 'Points are credited depending on the type and weight of waste submitted. For example, you get more points per kilogram of plastic than paper. All rates are transparent and displayed in the app.',
    'faq-q2': 'Where can I drop off waste?',
    'faq-a2': 'You can find the nearest drop-off point on the map in the app. We are constantly expanding our network of partner collection points to make recycling as convenient as possible.',
    'faq-q3': 'What can I spend points on?',
    'faq-a3': 'Points can be exchanged for discounts at stores, cafés, fitness clubs and other partner organizations. The full list of offers is available in the Bonuses section of your account.',
    'faq-q4': 'How is the system protected from fraud?',
    'faq-a4': 'We use QR codes, geolocation and automatic weighing to verify submissions. There are also limits on the number of operations and a full action history is maintained.',
    'faq-q5': 'Is registration free?',
    'faq-a5': 'Yes, registration and use of the platform are completely free for users. You pay nothing — you only earn points for recycling waste.',
    'faq-q6': 'How do I become a platform partner?',
    'faq-a6': 'For businesses, we offer several collaboration models. Submit a request via the form on the site, and our manager will contact you to discuss the terms.',
    'cta-badge': 'Join today',
    'cta-title': 'Start earning points for recycling',
    'cta-desc': 'Join thousands of users who are already turning care for the environment into real value. Registration is free and takes less than a minute.',
    'cta-btn1': 'Create account',
    'cta-btn2': 'Contact us',
    'footer-desc': 'The platform that makes waste recycling profitable for everyone.',
    'footer-col-platform': 'Platform',
    'footer-col-account': 'Account',
    'footer-col-support': 'Support',
    'footer-link-hiw': 'How it works',
    'footer-link-dashboard': 'Dashboard',
    'footer-link-partners': 'Partners',
    'footer-link-bonuses': 'Bonuses',
    'footer-link-login': 'Login',
    'footer-link-signup': 'Sign up',
    'footer-link-qr': 'QR code',
    'footer-link-contact': 'Contact',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'Email us',
    'footer-coming-soon': 'Coming soon',
    'footer-social-soon': 'Social media — coming soon',
    'footer-copyright': '© 2026 EcoPoints. All rights reserved.',
    'my-rewards': 'My Rewards',
    'catalog': 'Catalog',
    'no-redeemed': 'You haven\'t redeemed any rewards yet',
    'will-deduct': 'Points to be deducted:',
    'confirm-btn': 'Confirm',
    'cancel': 'Cancel',
    'redeemed-on': 'Redeemed',
    'spent': 'spent',
  },
  ru: {
    'how-it-works': 'Как это работает',
    benefits: 'Преимущества',
    partners: 'Партнёрам',
    faq: 'FAQ',
    dashboard: 'Кабинет',
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    theme: 'Тема',
    language: 'Язык',
    light: 'Светлая',
    dark: 'Тёмная',
    system: 'Система',
    start: 'Начать',
    open_menu: 'Открыть меню',
    close_menu: 'Закрыть меню',
    back: 'Личный кабинет',
    'qr-and-points': 'QR и баллы',
    welcome: 'Добро пожаловать!',
    'track-progress': 'Отслеживайте свой прогресс и получайте награды',
    'recent-activity': 'Последняя активность',
    'available-rewards': 'Доступные награды',
    'all-rewards': 'Все награды',
    'find-dropoff': 'Найти пункт приёма',
    'dropoff-count': 'Более 500 точек в вашем городе',
    'open-map': 'Открыть карту',
    'rewards-catalog': 'Каталог наград',
    'your-balance': 'Ваш баланс',
    'get-reward': 'Получить',
    'not-enough-points': 'Мало баллов',
    'points-needed': 'баллов не хватает',
    'redeem-soon': 'Обмен наград скоро появится',
    'open-cabinet': 'Открыть кабинет →',
    'qr-and-balance': 'QR-код и баланс →',
    'your-ecopoints-card': 'Ваша карта EcoPoints',
    'show-code': 'Покажите код на пункте приёма или поделитесь приглашением',
    balance: 'Баланс',
    'points-available': 'баллов доступно',
    'member-card': 'Карта участника',
    'member-card-desc': 'Сканируйте на пункте приёма для идентификации вашего аккаунта EcoPoints.',
    'invite-friend': 'Пригласить друга',
    'invite-friend-desc': 'Друг переходит по ссылке из кода и регистрируется — бонусы начисляются по правилам программы.',
    'invite-code': 'Код приглашения',
    'cat-all': 'Все',
    'cat-grocery': 'Продукты',
    'cat-cafe': 'Кафе',
    'cat-online': 'Онлайн',
    'cat-sport': 'Спорт',
    'cat-transport': 'Транспорт',
    'points-label': 'Баллы',
    'kg-recycled': 'Сдано кг',
    'rewards-count': 'Награды',
    'act-plastic': 'Сдано 5 кг пластика',
    'act-discount-cafe': 'Скидка 15% в Кофемании',
    'act-paper': 'Сдано 3 кг макулатуры',
    'act-bonus': 'Бонус за активность',
    'time-2h': '2 часа назад',
    'time-yesterday': 'Вчера',
    'time-3d': '3 дня назад',
    'time-week': 'Неделю назад',
    'points-word': 'баллов',
    'reward-perekrestok': 'Скидка 10% в Перекрёстке',
    'reward-perekrestok-desc': 'На любую покупку от 500 ₽',
    'reward-starbucks': 'Бесплатный кофе в Starbucks',
    'reward-starbucks-desc': 'Любой напиток до 500 мл',
    'reward-ozon': 'Скидка 20% на Ozon',
    'reward-ozon-desc': 'На заказ от 1000 ₽',
    'reward-kofemainia': 'Скидка 15% в Кофемании',
    'reward-kofemainia-desc': 'На все меню, кроме алкоголя',
    'reward-worldclass': 'Абонемент на 1 день в World Class',
    'reward-worldclass-desc': 'Доступ ко всем зонам клуба',
    'reward-vkusvill': 'Скидка 10% в ВкусВилл',
    'reward-vkusvill-desc': 'На весь ассортимент',
    'reward-yandex': 'Поездка на Яндекс Go',
    'reward-yandex-desc': 'Промокод на 150 ₽',
    'reward-lamoda': 'Скидка 25% в Lamoda',
    'reward-lamoda-desc': 'На первый заказ',
    'reward-fitnesshouse': 'Бесплатная тренировка в Фитнес Хаус',
    'reward-fitnesshouse-desc': 'Разовое посещение',
    'reward-magnit': 'Скидка 10% в Магните',
    'reward-magnit-desc': 'На покупку от 300 ₽',
    'reward-costa': 'Кофе в подарок в Costa Coffee',
    'reward-costa-desc': 'Любой напиток размера М',
    'reward-scooter': 'Самокат — 30 минут бесплатно',
    'reward-scooter-desc': 'Промокод на поездку',
    'map-title': 'Карта пунктов приёма',
    'map-all-types': 'Все',
    'map-use-location': 'Моё местоположение',
    'map-locating': 'Определяю...',
    'map-location-error': 'Местоположение недоступно',
    'map-points-found': 'пунктов',
    'map-nearest': 'Ближайший',
    'map-km': 'км',
    'map-hours': 'Часы работы',
    'map-pts-per-kg': 'баллов/кг',
    'map-route': 'Маршрут',
    'map-you-are-here': 'Вы здесь',
    'waste-plastic': 'Пластик',
    'waste-paper': 'Бумага',
    'waste-glass': 'Стекло',
    'waste-metal': 'Металл',
    'waste-electronics': 'Электроника',
    'waste-organic': 'Органика',
    'hero-badge': 'Экология + Выгода = EcoPoints',
    'hero-h1-1': 'Превращаем отходы',
    'hero-h1-2': 'в ценность',
    'hero-desc': 'Сдавайте мусор на переработку, копите баллы и получайте реальные скидки от партнёров. Забота об экологии теперь выгодна.',
    'hero-btn-primary': 'Начать копить баллы',
    'hero-btn-secondary': 'Узнать больше',
    'hero-stat-dropoff': 'Точек сдачи',
    'hero-stat-partners': 'Партнёров',
    'hero-stat-users': 'Пользователей',
    'hiw-badge': 'Простой процесс',
    'hiw-title': 'Как это работает',
    'hiw-desc': 'От регистрации до получения реальных бонусов — всего 4 простых шага',
    'hiw-step1-title': 'Регистрация',
    'hiw-step1-desc': 'Создайте аккаунт за пару минут. Это бесплатно и займёт минимум времени.',
    'hiw-step2-title': 'Сдайте отходы',
    'hiw-step2-desc': 'Найдите ближайшую точку сдачи, отсканируйте QR-код и сдайте отсортированный мусор.',
    'hiw-step3-title': 'Получите баллы',
    'hiw-step3-desc': 'Система автоматически начислит баллы в зависимости от типа и веса сданных отходов.',
    'hiw-step4-title': 'Обменяйте на бонусы',
    'hiw-step4-desc': 'Используйте накопленные баллы для получения скидок и предложений от партнёров.',
    'ben-badge': 'Выгода для всех',
    'ben-title': 'Преимущества платформы',
    'ben-desc': 'EcoPoints создаёт ценность для пользователей, бизнеса и окружающей среды',
    'ben-for-users': 'Для пользователей',
    'ben-for-biz': 'Для бизнеса',
    'ben-u1-title': 'Реальная выгода',
    'ben-u1-desc': 'Получайте скидки и бонусы от сотен партнёров за простое действие — сдачу отходов на переработку.',
    'ben-u2-title': 'Личный прогресс',
    'ben-u2-desc': 'Отслеживайте свой вклад в экологию: вес сданных отходов, заработанные баллы и сэкономленные ресурсы.',
    'ben-u3-title': 'Прозрачная система',
    'ben-u3-desc': 'Все операции фиксируются. Вы всегда знаете, сколько сдали, сколько заработали и куда потратили.',
    'ben-b1-title': 'Новые клиенты',
    'ben-b1-desc': 'Получите доступ к аудитории экологически сознательных пользователей, готовых к покупкам.',
    'ben-b2-title': 'ESG-имидж',
    'ben-b2-desc': 'Укрепите репутацию социально ответственной компании и соответствуйте стандартам устойчивого развития.',
    'ben-b3-title': 'Эффективный маркетинг',
    'ben-b3-desc': 'Привлекайте клиентов дешевле, чем через традиционную рекламу, с высокой конверсией.',
    'par-badge': 'Для бизнеса',
    'par-h1': 'Станьте',
    'par-h2': 'партнёром',
    'par-desc': 'Привлекайте экологически сознательных клиентов, которые уже мотивированы к покупке. Наша платформа соединяет ваш бизнес с аудиторией, ценящей устойчивое развитие.',
    'par-feat1': 'Доступ к базе активных пользователей',
    'par-feat2': 'Гибкие условия сотрудничества',
    'par-feat3': 'Аналитика и отчётность',
    'par-btn': 'Стать партнёром',
    'par-cat-1': 'Кафе и рестораны',
    'par-cat-2': 'Супермаркеты',
    'par-cat-3': 'Фитнес-клубы',
    'par-cat-4': 'Онлайн-магазины',
    'par-cat-5': 'Кинотеатры',
    'par-cat-6': 'Аптеки',
    'faq-badge': 'Поддержка',
    'faq-title': 'Частые вопросы',
    'faq-desc': 'Ответы на популярные вопросы о платформе',
    'faq-q1': 'Как начисляются баллы?',
    'faq-a1': 'Баллы начисляются в зависимости от типа и веса сданных отходов. Например, за килограмм пластика вы получите больше баллов, чем за бумагу. Все тарифы прозрачны и отображаются в приложении.',
    'faq-q2': 'Где можно сдать отходы?',
    'faq-a2': 'Найти ближайшую точку сдачи можно на карте в приложении. Мы постоянно расширяем сеть партнёрских пунктов приёма, чтобы сделать переработку максимально удобной.',
    'faq-q3': 'На что можно потратить баллы?',
    'faq-a3': 'Баллы можно обменять на скидки в магазинах, кафе, фитнес-клубах и других партнёрских организациях. Полный список предложений доступен в разделе «Бонусы» в личном кабинете.',
    'faq-q4': 'Как защищена система от мошенничества?',
    'faq-a4': 'Мы используем QR-коды, геолокацию и автоматическое взвешивание для верификации сдачи. Также действуют лимиты на количество операций и ведётся полная история действий.',
    'faq-q5': 'Регистрация бесплатная?',
    'faq-a5': 'Да, регистрация и использование платформы полностью бесплатны для пользователей. Вы не платите ничего — только зарабатываете баллы за сдачу отходов.',
    'faq-q6': 'Как стать партнёром платформы?',
    'faq-a6': 'Для бизнеса мы предлагаем несколько моделей сотрудничества. Оставьте заявку через форму на сайте, и наш менеджер свяжется с вами для обсуждения условий.',
    'cta-badge': 'Присоединяйтесь сегодня',
    'cta-title': 'Начните копить баллы за переработку',
    'cta-desc': 'Присоединяйтесь к тысячам пользователей, которые уже превращают заботу об экологии в реальную выгоду. Регистрация бесплатна и занимает меньше минуты.',
    'cta-btn1': 'Создать аккаунт',
    'cta-btn2': 'Связаться с нами',
    'footer-desc': 'Платформа, которая делает переработку отходов выгодной для всех.',
    'footer-col-platform': 'Платформа',
    'footer-col-account': 'Аккаунт',
    'footer-col-support': 'Поддержка',
    'footer-link-hiw': 'Как это работает',
    'footer-link-dashboard': 'Личный кабинет',
    'footer-link-partners': 'Партнёры',
    'footer-link-bonuses': 'Бонусы',
    'footer-link-login': 'Вход',
    'footer-link-signup': 'Регистрация',
    'footer-link-qr': 'QR-код',
    'footer-link-contact': 'Контакты',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'Написать нам',
    'footer-coming-soon': 'Скоро',
    'footer-social-soon': 'Соцсети — скоро',
    'footer-copyright': '© 2026 EcoPoints. Все права защищены.',
    'my-rewards': 'Мои награды',
    'catalog': 'Каталог',
    'no-redeemed': 'Вы ещё не получили ни одной награды',
    'will-deduct': 'Будет списано:',
    'confirm-btn': 'Подтвердить',
    'cancel': 'Отмена',
    'redeemed-on': 'Получено',
    'spent': 'баллов',
  },
  ko: {
    'how-it-works': '작동 원리',
    benefits: '이점',
    partners: '파트너',
    faq: '자주 묻는 질문',
    dashboard: '대시보드',
    login: '로그인',
    signup: '가입',
    logout: '로그아웃',
    theme: '테마',
    language: '언어',
    light: '밝음',
    dark: '어두움',
    system: '시스템',
    start: '시작하기',
    open_menu: '메뉴 열기',
    close_menu: '메뉴 닫기',
    back: '대시보드',
    'qr-and-points': 'QR 및 포인트',
    welcome: '환영합니다!',
    'track-progress': '진행 상황을 추적하고 보상을 받으세요',
    'recent-activity': '최근 활동',
    'available-rewards': '사용 가능한 보상',
    'all-rewards': '모든 보상',
    'find-dropoff': '수거 지점 찾기',
    'dropoff-count': '도시 내 500개 이상 지점',
    'open-map': '지도 열기',
    'rewards-catalog': '보상 카탈로그',
    'your-balance': '잔액',
    'get-reward': '받기',
    'not-enough-points': '포인트 부족',
    'points-needed': '포인트 더 필요',
    'redeem-soon': '곧 교환 가능',
    'open-cabinet': '대시보드 열기 →',
    'qr-and-balance': 'QR 코드 및 잔액 →',
    'your-ecopoints-card': 'EcoPoints 카드',
    'show-code': '수거 지점에서 코드를 보여주거나 초대장을 공유하세요',
    balance: '잔액',
    'points-available': '포인트 사용 가능',
    'member-card': '회원 카드',
    'member-card-desc': '수거 지점에서 스캔하여 EcoPoints 계정을 확인하세요.',
    'invite-friend': '친구 초대',
    'invite-friend-desc': '친구가 링크를 통해 가입하면 프로그램 규정에 따라 보너스가 지급됩니다.',
    'invite-code': '초대 코드',
    'cat-all': '전체',
    'cat-grocery': '식료품',
    'cat-cafe': '카페',
    'cat-online': '온라인',
    'cat-sport': '스포츠',
    'cat-transport': '교통',
    'points-label': '포인트',
    'kg-recycled': '재활용 kg',
    'rewards-count': '보상',
    'act-plastic': '플라스틱 5kg 재활용',
    'act-discount-cafe': 'Kofemainia 15% 할인',
    'act-paper': '종이 3kg 재활용',
    'act-bonus': '활동 보너스',
    'time-2h': '2시간 전',
    'time-yesterday': '어제',
    'time-3d': '3일 전',
    'time-week': '1주일 전',
    'points-word': '포인트',
    'reward-perekrestok': 'Perekrestok 10% 할인',
    'reward-perekrestok-desc': '500 ₽ 이상 구매 시',
    'reward-starbucks': 'Starbucks 무료 커피',
    'reward-starbucks-desc': '500ml 이하 음료',
    'reward-ozon': 'Ozon 20% 할인',
    'reward-ozon-desc': '1000 ₽ 이상 주문',
    'reward-kofemainia': 'Kofemainia 15% 할인',
    'reward-kofemainia-desc': '주류 제외 전 메뉴',
    'reward-worldclass': 'World Class 1일 이용권',
    'reward-worldclass-desc': '전 구역 이용 가능',
    'reward-vkusvill': 'VkusVill 10% 할인',
    'reward-vkusvill-desc': '전 상품 적용',
    'reward-yandex': 'Yandex Go 탑승',
    'reward-yandex-desc': '150 ₽ 프로모 코드',
    'reward-lamoda': 'Lamoda 25% 할인',
    'reward-lamoda-desc': '첫 주문',
    'reward-fitnesshouse': 'Fitness House 무료 운동',
    'reward-fitnesshouse-desc': '1회 방문',
    'reward-magnit': 'Magnit 10% 할인',
    'reward-magnit-desc': '300 ₽ 이상 구매',
    'reward-costa': 'Costa Coffee 무료 커피',
    'reward-costa-desc': 'M 사이즈 음료',
    'reward-scooter': '전동킥보드 30분 무료',
    'reward-scooter-desc': '탑승 프로모 코드',
    'map-title': '수거 지점 지도',
    'map-all-types': '전체',
    'map-use-location': '내 위치',
    'map-locating': '위치 확인 중...',
    'map-location-error': '위치 사용 불가',
    'map-points-found': '지점 발견',
    'map-nearest': '가장 가까운',
    'map-km': 'km',
    'map-hours': '영업시간',
    'map-pts-per-kg': 'pts/kg',
    'map-route': '경로',
    'map-you-are-here': '현재 위치',
    'waste-plastic': '플라스틱',
    'waste-paper': '종이',
    'waste-glass': '유리',
    'waste-metal': '금속',
    'waste-electronics': '전자기기',
    'waste-organic': '유기물',
    'hero-badge': '환경 + 혜택 = EcoPoints',
    'hero-h1-1': '쓰레기를',
    'hero-h1-2': '가치로 바꿉니다',
    'hero-desc': '쓰레기를 재활용하고 포인트를 모아 파트너사의 실제 할인을 받으세요. 환경 보호가 이제 보람 있습니다.',
    'hero-btn-primary': '포인트 적립 시작',
    'hero-btn-secondary': '더 알아보기',
    'hero-stat-dropoff': '수거 지점',
    'hero-stat-partners': '파트너',
    'hero-stat-users': '사용자',
    'hiw-badge': '간단한 과정',
    'hiw-title': '사용 방법',
    'hiw-desc': '가입부터 실제 보너스까지 — 단 4단계',
    'hiw-step1-title': '회원가입',
    'hiw-step1-desc': '몇 분 만에 계정을 만드세요. 무료이며 최소한의 시간만 걸립니다.',
    'hiw-step2-title': '폐기물 제출',
    'hiw-step2-desc': '가장 가까운 수거 지점을 찾아 QR 코드를 스캔하고 분리된 쓰레기를 제출하세요.',
    'hiw-step3-title': '포인트 획득',
    'hiw-step3-desc': '시스템이 제출된 폐기물의 종류와 무게에 따라 자동으로 포인트를 적립합니다.',
    'hiw-step4-title': '보너스로 교환',
    'hiw-step4-desc': '누적된 포인트를 사용하여 파트너로부터 할인과 혜택을 받으세요.',
    'ben-badge': '모두를 위한 가치',
    'ben-title': '플랫폼 혜택',
    'ben-desc': 'EcoPoints는 사용자, 기업 및 환경을 위한 가치를 창출합니다',
    'ben-for-users': '사용자를 위한',
    'ben-for-biz': '기업을 위한',
    'ben-u1-title': '실제 혜택',
    'ben-u1-desc': '수백 개의 파트너로부터 간단한 행동(폐기물 재활용)으로 할인과 보너스를 받으세요.',
    'ben-u2-title': '개인 발전',
    'ben-u2-desc': '환경 기여도를 추적하세요: 재활용된 폐기물 무게, 획득한 포인트 및 절약된 자원.',
    'ben-u3-title': '투명한 시스템',
    'ben-u3-desc': '모든 거래가 기록됩니다. 얼마나 재활용하고, 얼마나 벌고, 어디에 썼는지 항상 알 수 있습니다.',
    'ben-b1-title': '새로운 고객',
    'ben-b1-desc': '구매할 의향이 있는 친환경 사용자 그룹에 액세스하세요.',
    'ben-b2-title': 'ESG 이미지',
    'ben-b2-desc': '사회적 책임 기업으로서의 명성을 강화하고 지속 가능한 개발 기준을 충족하세요.',
    'ben-b3-title': '효과적인 마케팅',
    'ben-b3-desc': '높은 전환율로 기존 광고보다 저렴하게 고객을 유치하세요.',
    'par-badge': '기업을 위한',
    'par-h1': '파트너가',
    'par-h2': '되어보세요',
    'par-desc': '이미 구매 의향이 있는 친환경 고객을 유치하세요. 저희 플랫폼은 귀사의 비즈니스를 지속 가능한 발전을 중시하는 고객과 연결합니다.',
    'par-feat1': '활성 사용자 베이스 접근',
    'par-feat2': '유연한 파트너십 조건',
    'par-feat3': '분석 및 리포팅',
    'par-btn': '파트너 되기',
    'par-cat-1': '카페 & 레스토랑',
    'par-cat-2': '슈퍼마켓',
    'par-cat-3': '피트니스 클럽',
    'par-cat-4': '온라인 쇼핑',
    'par-cat-5': '영화관',
    'par-cat-6': '약국',
    'faq-badge': '지원',
    'faq-title': '자주 묻는 질문',
    'faq-desc': '플랫폼에 관한 인기 질문에 대한 답변',
    'faq-q1': '포인트는 어떻게 적립되나요?',
    'faq-a1': '포인트는 제출된 폐기물의 종류와 무게에 따라 적립됩니다. 예를 들어 플라스틱 1kg은 종이보다 더 많은 포인트를 얻습니다. 모든 요금제는 투명하며 앱에서 확인할 수 있습니다.',
    'faq-q2': '폐기물은 어디에 제출하나요?',
    'faq-a2': '앱의 지도에서 가장 가까운 수거 지점을 찾을 수 있습니다. 재활용을 최대한 편리하게 만들기 위해 파트너 수거 지점 네트워크를 지속적으로 확장하고 있습니다.',
    'faq-q3': '포인트로 무엇을 살 수 있나요?',
    'faq-a3': '포인트는 상점, 카페, 피트니스 클럽 및 기타 파트너 기관의 할인으로 교환할 수 있습니다. 전체 혜택 목록은 개인 계정의 보너스 섹션에서 확인할 수 있습니다.',
    'faq-q4': '사기로부터 시스템이 어떻게 보호되나요?',
    'faq-a4': 'QR 코드, 위치 정보 및 자동 계량을 사용하여 제출을 확인합니다. 또한 작업 수에 제한이 있으며 완전한 활동 내역이 유지됩니다.',
    'faq-q5': '가입이 무료인가요?',
    'faq-a5': '네, 플랫폼 등록 및 이용은 사용자에게 완전히 무료입니다. 아무것도 지불하지 않고 폐기물 재활용으로 포인트만 적립합니다.',
    'faq-q6': '플랫폼 파트너가 되려면 어떻게 하나요?',
    'faq-a6': '기업을 위해 여러 협력 모델을 제공합니다. 사이트의 양식을 통해 신청서를 제출하면 담당자가 조건 논의를 위해 연락드립니다.',
    'cta-badge': '오늘 참여하세요',
    'cta-title': '재활용으로 포인트 적립 시작',
    'cta-desc': '이미 환경 보호를 실제 혜택으로 바꾸고 있는 수천 명의 사용자와 함께하세요. 가입은 무료이며 1분도 채 걸리지 않습니다.',
    'cta-btn1': '계정 만들기',
    'cta-btn2': '문의하기',
    'footer-desc': '모두에게 폐기물 재활용을 이롭게 만드는 플랫폼.',
    'footer-col-platform': '플랫폼',
    'footer-col-account': '계정',
    'footer-col-support': '지원',
    'footer-link-hiw': '사용 방법',
    'footer-link-dashboard': '대시보드',
    'footer-link-partners': '파트너',
    'footer-link-bonuses': '보너스',
    'footer-link-login': '로그인',
    'footer-link-signup': '가입',
    'footer-link-qr': 'QR 코드',
    'footer-link-contact': '연락처',
    'footer-link-faq': 'FAQ',
    'footer-link-write': '이메일 보내기',
    'footer-coming-soon': '출시 예정',
    'footer-social-soon': '소셜 미디어 — 출시 예정',
    'footer-copyright': '© 2026 EcoPoints. 모든 권리 보유.',
    'my-rewards': '내 보상',
    'catalog': '카탈로그',
    'no-redeemed': '아직 교환한 보상이 없습니다',
    'will-deduct': '차감 포인트:',
    'confirm-btn': '확인',
    'cancel': '취소',
    'redeemed-on': '교환일',
    'spent': '포인트 사용',
  },
  es: {
    'how-it-works': 'Cómo funciona',
    benefits: 'Beneficios',
    partners: 'Socios',
    faq: 'Preguntas frecuentes',
    dashboard: 'Panel de control',
    login: 'Iniciar sesión',
    signup: 'Registrarse',
    logout: 'Cerrar sesión',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    start: 'Comenzar',
    open_menu: 'Abrir menú',
    close_menu: 'Cerrar menú',
    back: 'Panel',
    'qr-and-points': 'QR y Puntos',
    welcome: '¡Bienvenido!',
    'track-progress': 'Sigue tu progreso y obtén recompensas',
    'recent-activity': 'Actividad Reciente',
    'available-rewards': 'Recompensas Disponibles',
    'all-rewards': 'Todas las Recompensas',
    'find-dropoff': 'Encontrar Punto de Entrega',
    'dropoff-count': 'Más de 500 puntos en tu ciudad',
    'open-map': 'Abrir Mapa',
    'rewards-catalog': 'Catálogo de Recompensas',
    'your-balance': 'Tu saldo',
    'get-reward': 'Obtener',
    'not-enough-points': 'Sin puntos',
    'points-needed': 'puntos más necesarios',
    'redeem-soon': 'Canje próximamente',
    'open-cabinet': 'Abrir Panel →',
    'qr-and-balance': 'Código QR y saldo →',
    'your-ecopoints-card': 'Tu Tarjeta EcoPoints',
    'show-code': 'Muestra el código en el punto de entrega o comparte una invitación',
    balance: 'Saldo',
    'points-available': 'puntos disponibles',
    'member-card': 'Tarjeta de Miembro',
    'member-card-desc': 'Escanea en el punto de entrega para identificar tu cuenta EcoPoints.',
    'invite-friend': 'Invitar a un Amigo',
    'invite-friend-desc': 'Un amigo sigue el enlace y se registra — los bonos se acreditan según las reglas del programa.',
    'invite-code': 'Código de invitación',
    'cat-all': 'Todo',
    'cat-grocery': 'Alimentación',
    'cat-cafe': 'Café',
    'cat-online': 'Online',
    'cat-sport': 'Deporte',
    'cat-transport': 'Transporte',
    'points-label': 'Puntos',
    'kg-recycled': 'kg reciclados',
    'rewards-count': 'Recompensas',
    'act-plastic': 'Reciclados 5 kg de plástico',
    'act-discount-cafe': '15% de descuento en Kofemainia',
    'act-paper': 'Reciclados 3 kg de papel',
    'act-bonus': 'Bono de actividad',
    'time-2h': 'Hace 2 horas',
    'time-yesterday': 'Ayer',
    'time-3d': 'Hace 3 días',
    'time-week': 'Hace una semana',
    'points-word': 'pts',
    'reward-perekrestok': '10% de descuento en Perekrestok',
    'reward-perekrestok-desc': 'Compra desde 500 ₽',
    'reward-starbucks': 'Café gratis en Starbucks',
    'reward-starbucks-desc': 'Bebida hasta 500 ml',
    'reward-ozon': '20% de descuento en Ozon',
    'reward-ozon-desc': 'Pedido desde 1000 ₽',
    'reward-kofemainia': '15% de descuento en Kofemainia',
    'reward-kofemainia-desc': 'Todo el menú excepto alcohol',
    'reward-worldclass': 'Pase de 1 día en World Class',
    'reward-worldclass-desc': 'Acceso a todas las zonas',
    'reward-vkusvill': '10% de descuento en VkusVill',
    'reward-vkusvill-desc': 'Todo el surtido',
    'reward-yandex': 'Viaje en Yandex Go',
    'reward-yandex-desc': 'Código promo por 150 ₽',
    'reward-lamoda': '25% de descuento en Lamoda',
    'reward-lamoda-desc': 'Primer pedido',
    'reward-fitnesshouse': 'Entrenamiento gratis en Fitness House',
    'reward-fitnesshouse-desc': 'Una visita',
    'reward-magnit': '10% de descuento en Magnit',
    'reward-magnit-desc': 'Compra desde 300 ₽',
    'reward-costa': 'Café gratis en Costa Coffee',
    'reward-costa-desc': 'Bebida tamaño M',
    'reward-scooter': 'Patinete — 30 min gratis',
    'reward-scooter-desc': 'Código promo de viaje',
    'map-title': 'Mapa de Puntos de Entrega',
    'map-all-types': 'Todos',
    'map-use-location': 'Mi Ubicación',
    'map-locating': 'Ubicando...',
    'map-location-error': 'Ubicación no disponible',
    'map-points-found': 'puntos encontrados',
    'map-nearest': 'Más cercano',
    'map-km': 'km',
    'map-hours': 'Horario',
    'map-pts-per-kg': 'pts/kg',
    'map-route': 'Ruta',
    'map-you-are-here': 'Usted está aquí',
    'waste-plastic': 'Plástico',
    'waste-paper': 'Papel',
    'waste-glass': 'Vidrio',
    'waste-metal': 'Metal',
    'waste-electronics': 'Electrónica',
    'waste-organic': 'Orgánico',
    'hero-badge': 'Ecología + Ahorro = EcoPoints',
    'hero-h1-1': 'Convertimos residuos',
    'hero-h1-2': 'en valor',
    'hero-desc': 'Lleva tus residuos al reciclaje, acumula puntos y obtén descuentos reales de nuestros socios. Cuidar el medio ambiente ahora tiene recompensa.',
    'hero-btn-primary': 'Empezar a ganar puntos',
    'hero-btn-secondary': 'Saber más',
    'hero-stat-dropoff': 'Puntos de entrega',
    'hero-stat-partners': 'Socios',
    'hero-stat-users': 'Usuarios',
    'hiw-badge': 'Proceso simple',
    'hiw-title': 'Cómo funciona',
    'hiw-desc': 'Desde el registro hasta los bonos reales — solo 4 pasos simples',
    'hiw-step1-title': 'Regístrate',
    'hiw-step1-desc': 'Crea una cuenta en un par de minutos. Es gratis y toma el mínimo tiempo.',
    'hiw-step2-title': 'Entrega tus residuos',
    'hiw-step2-desc': 'Encuentra el punto de entrega más cercano, escanea el código QR y entrega tus residuos clasificados.',
    'hiw-step3-title': 'Obtén puntos',
    'hiw-step3-desc': 'El sistema acreditará automáticamente puntos según el tipo y peso de los residuos entregados.',
    'hiw-step4-title': 'Canjea por bonos',
    'hiw-step4-desc': 'Usa los puntos acumulados para obtener descuentos y ofertas de nuestros socios.',
    'ben-badge': 'Valor para todos',
    'ben-title': 'Ventajas de la plataforma',
    'ben-desc': 'EcoPoints crea valor para usuarios, empresas y el medio ambiente',
    'ben-for-users': 'Para usuarios',
    'ben-for-biz': 'Para empresas',
    'ben-u1-title': 'Ahorro real',
    'ben-u1-desc': 'Obtén descuentos y bonos de cientos de socios por una acción simple — reciclar tus residuos.',
    'ben-u2-title': 'Progreso personal',
    'ben-u2-desc': 'Sigue tu contribución ambiental: peso de residuos reciclados, puntos ganados y recursos ahorrados.',
    'ben-u3-title': 'Sistema transparente',
    'ben-u3-desc': 'Todas las operaciones quedan registradas. Siempre sabes cuánto reciclaste, ganaste y gastaste.',
    'ben-b1-title': 'Nuevos clientes',
    'ben-b1-desc': 'Accede a una audiencia de usuarios conscientes del medio ambiente listos para comprar.',
    'ben-b2-title': 'Imagen ESG',
    'ben-b2-desc': 'Fortalece tu reputación como empresa socialmente responsable y cumple con los estándares de desarrollo sostenible.',
    'ben-b3-title': 'Marketing efectivo',
    'ben-b3-desc': 'Atrae clientes más barato que con publicidad tradicional, con alta conversión.',
    'par-badge': 'Para empresas',
    'par-h1': 'Conviértete en',
    'par-h2': 'socio',
    'par-desc': 'Atrae clientes conscientes del medio ambiente que ya están motivados a comprar. Nuestra plataforma conecta tu negocio con una audiencia que valora el desarrollo sostenible.',
    'par-feat1': 'Acceso a una base de usuarios activos',
    'par-feat2': 'Condiciones de asociación flexibles',
    'par-feat3': 'Analítica e informes',
    'par-btn': 'Convertirse en socio',
    'par-cat-1': 'Cafés y restaurantes',
    'par-cat-2': 'Supermercados',
    'par-cat-3': 'Gimnasios',
    'par-cat-4': 'Tiendas online',
    'par-cat-5': 'Cines',
    'par-cat-6': 'Farmacias',
    'faq-badge': 'Soporte',
    'faq-title': 'Preguntas frecuentes',
    'faq-desc': 'Respuestas a preguntas populares sobre la plataforma',
    'faq-q1': '¿Cómo se acreditan los puntos?',
    'faq-a1': 'Los puntos se acreditan según el tipo y peso de los residuos entregados. Por ejemplo, por un kilogramo de plástico obtienes más puntos que por papel. Todas las tarifas son transparentes y se muestran en la app.',
    'faq-q2': '¿Dónde puedo entregar residuos?',
    'faq-a2': 'Puedes encontrar el punto de entrega más cercano en el mapa de la app. Expandimos constantemente nuestra red de puntos de recolección para hacer el reciclaje lo más conveniente posible.',
    'faq-q3': '¿En qué puedo gastar los puntos?',
    'faq-a3': 'Los puntos se pueden canjear por descuentos en tiendas, cafés, gimnasios y otras organizaciones asociadas. La lista completa de ofertas está disponible en la sección Bonos de tu cuenta.',
    'faq-q4': '¿Cómo está protegido el sistema contra el fraude?',
    'faq-a4': 'Usamos códigos QR, geolocalización y pesaje automático para verificar las entregas. También hay límites en el número de operaciones y se mantiene un historial completo de acciones.',
    'faq-q5': '¿El registro es gratuito?',
    'faq-a5': 'Sí, el registro y el uso de la plataforma son completamente gratuitos para los usuarios. No pagas nada — solo ganas puntos por reciclar residuos.',
    'faq-q6': '¿Cómo me convierto en socio de la plataforma?',
    'faq-a6': 'Para empresas ofrecemos varios modelos de colaboración. Envía una solicitud a través del formulario del sitio y nuestro gestor te contactará para discutir las condiciones.',
    'cta-badge': 'Únete hoy',
    'cta-title': 'Empieza a ganar puntos por reciclar',
    'cta-desc': 'Únete a miles de usuarios que ya convierten el cuidado del medio ambiente en valor real. El registro es gratuito y tarda menos de un minuto.',
    'cta-btn1': 'Crear cuenta',
    'cta-btn2': 'Contactarnos',
    'footer-desc': 'La plataforma que hace que el reciclaje de residuos sea rentable para todos.',
    'footer-col-platform': 'Plataforma',
    'footer-col-account': 'Cuenta',
    'footer-col-support': 'Soporte',
    'footer-link-hiw': 'Cómo funciona',
    'footer-link-dashboard': 'Panel',
    'footer-link-partners': 'Socios',
    'footer-link-bonuses': 'Bonos',
    'footer-link-login': 'Iniciar sesión',
    'footer-link-signup': 'Registrarse',
    'footer-link-qr': 'Código QR',
    'footer-link-contact': 'Contacto',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'Escribirnos',
    'footer-coming-soon': 'Próximamente',
    'footer-social-soon': 'Redes sociales — próximamente',
    'footer-copyright': '© 2026 EcoPoints. Todos los derechos reservados.',
    'my-rewards': 'Mis recompensas',
    'catalog': 'Catálogo',
    'no-redeemed': 'Aún no has canjeado ninguna recompensa',
    'will-deduct': 'Se descontarán:',
    'confirm-btn': 'Confirmar',
    'cancel': 'Cancelar',
    'redeemed-on': 'Canjeado el',
    'spent': 'pts gastados',
  },
  fr: {
    'how-it-works': 'Comment ça marche',
    benefits: 'Avantages',
    partners: 'Partenaires',
    faq: 'FAQ',
    dashboard: 'Tableau de bord',
    login: 'Connexion',
    signup: "S'inscrire",
    logout: 'Déconnexion',
    theme: 'Thème',
    language: 'Langue',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    start: 'Commencer',
    open_menu: 'Ouvrir le menu',
    close_menu: 'Fermer le menu',
    back: 'Tableau de bord',
    'qr-and-points': 'QR et Points',
    welcome: 'Bienvenue !',
    'track-progress': 'Suivez vos progrès et obtenez des récompenses',
    'recent-activity': 'Activité Récente',
    'available-rewards': 'Récompenses Disponibles',
    'all-rewards': 'Toutes les Récompenses',
    'find-dropoff': 'Trouver un Point de Dépôt',
    'dropoff-count': 'Plus de 500 points dans votre ville',
    'open-map': 'Ouvrir la Carte',
    'rewards-catalog': 'Catalogue de Récompenses',
    'your-balance': 'Votre solde',
    'get-reward': 'Obtenir',
    'not-enough-points': 'Pas assez',
    'points-needed': 'points manquants',
    'redeem-soon': 'Échange bientôt disponible',
    'open-cabinet': 'Ouvrir le tableau →',
    'qr-and-balance': 'QR code et solde →',
    'your-ecopoints-card': 'Votre Carte EcoPoints',
    'show-code': 'Montrez le code au point de dépôt ou partagez une invitation',
    balance: 'Solde',
    'points-available': 'points disponibles',
    'member-card': 'Carte Membre',
    'member-card-desc': "Scannez au point de dépôt pour identifier votre compte EcoPoints.",
    'invite-friend': 'Inviter un Ami',
    'invite-friend-desc': "Un ami suit le lien et s'inscrit — les bonus sont crédités selon les règles du programme.",
    'invite-code': "Code d'invitation",
    'cat-all': 'Tout',
    'cat-grocery': 'Alimentation',
    'cat-cafe': 'Café',
    'cat-online': 'En ligne',
    'cat-sport': 'Sport',
    'cat-transport': 'Transport',
    'points-label': 'Points',
    'kg-recycled': 'kg recyclés',
    'rewards-count': 'Récompenses',
    'act-plastic': '5 kg de plastique recyclés',
    'act-discount-cafe': '-15% chez Kofemainia',
    'act-paper': '3 kg de papier recyclés',
    'act-bonus': 'Bonus d\'activité',
    'time-2h': 'Il y a 2 heures',
    'time-yesterday': 'Hier',
    'time-3d': 'Il y a 3 jours',
    'time-week': 'Il y a une semaine',
    'points-word': 'pts',
    'reward-perekrestok': '-10% chez Perekrestok',
    'reward-perekrestok-desc': 'Achat à partir de 500 ₽',
    'reward-starbucks': 'Café offert chez Starbucks',
    'reward-starbucks-desc': 'Boisson jusqu\'à 500 ml',
    'reward-ozon': '-20% sur Ozon',
    'reward-ozon-desc': 'Commande à partir de 1000 ₽',
    'reward-kofemainia': '-15% chez Kofemainia',
    'reward-kofemainia-desc': 'Tout le menu sauf alcool',
    'reward-worldclass': 'Pass 1 jour chez World Class',
    'reward-worldclass-desc': 'Accès à toutes les zones',
    'reward-vkusvill': '-10% chez VkusVill',
    'reward-vkusvill-desc': 'Tout l\'assortiment',
    'reward-yandex': 'Trajet Yandex Go',
    'reward-yandex-desc': 'Code promo de 150 ₽',
    'reward-lamoda': '-25% chez Lamoda',
    'reward-lamoda-desc': 'Première commande',
    'reward-fitnesshouse': 'Séance gratuite chez Fitness House',
    'reward-fitnesshouse-desc': 'Visite unique',
    'reward-magnit': '-10% chez Magnit',
    'reward-magnit-desc': 'Achat à partir de 300 ₽',
    'reward-costa': 'Café offert chez Costa Coffee',
    'reward-costa-desc': 'Boisson taille M',
    'reward-scooter': 'Trottinette — 30 min offerts',
    'reward-scooter-desc': 'Code promo de trajet',
    'map-title': 'Carte des Points de Collecte',
    'map-all-types': 'Tous',
    'map-use-location': 'Ma Position',
    'map-locating': 'Localisation...',
    'map-location-error': 'Position indisponible',
    'map-points-found': 'points trouvés',
    'map-nearest': 'Le plus proche',
    'map-km': 'km',
    'map-hours': 'Horaires',
    'map-pts-per-kg': 'pts/kg',
    'map-route': 'Itinéraire',
    'map-you-are-here': 'Vous êtes ici',
    'waste-plastic': 'Plastique',
    'waste-paper': 'Papier',
    'waste-glass': 'Verre',
    'waste-metal': 'Métal',
    'waste-electronics': 'Électronique',
    'waste-organic': 'Organique',
    'hero-badge': 'Écologie + Économies = EcoPoints',
    'hero-h1-1': 'Nous transformons les déchets',
    'hero-h1-2': 'en valeur',
    'hero-desc': "Recyclez vos déchets, accumulez des points et obtenez de vraies réductions auprès de nos partenaires. Prendre soin de l'environnement est désormais rentable.",
    'hero-btn-primary': 'Commencer à gagner des points',
    'hero-btn-secondary': 'En savoir plus',
    'hero-stat-dropoff': 'Points de collecte',
    'hero-stat-partners': 'Partenaires',
    'hero-stat-users': 'Utilisateurs',
    'hiw-badge': 'Processus simple',
    'hiw-title': 'Comment ça marche',
    'hiw-desc': "De l'inscription aux vrais bonus — seulement 4 étapes simples",
    'hiw-step1-title': 'Inscription',
    'hiw-step1-desc': "Créez un compte en quelques minutes. C'est gratuit et prend un minimum de temps.",
    'hiw-step2-title': 'Déposez vos déchets',
    'hiw-step2-desc': 'Trouvez le point de dépôt le plus proche, scannez le code QR et déposez vos déchets triés.',
    'hiw-step3-title': 'Gagnez des points',
    'hiw-step3-desc': 'Le système créditera automatiquement des points en fonction du type et du poids des déchets déposés.',
    'hiw-step4-title': 'Échangez contre des bonus',
    'hiw-step4-desc': 'Utilisez les points accumulés pour obtenir des réductions et des offres de nos partenaires.',
    'ben-badge': 'Valeur pour tous',
    'ben-title': 'Avantages de la plateforme',
    'ben-desc': "EcoPoints crée de la valeur pour les utilisateurs, les entreprises et l'environnement",
    'ben-for-users': 'Pour les utilisateurs',
    'ben-for-biz': 'Pour les entreprises',
    'ben-u1-title': 'Économies réelles',
    'ben-u1-desc': 'Obtenez des réductions et des bonus de centaines de partenaires pour une action simple — recycler vos déchets.',
    'ben-u2-title': 'Progrès personnel',
    'ben-u2-desc': 'Suivez votre contribution environnementale : poids des déchets recyclés, points gagnés et ressources économisées.',
    'ben-u3-title': 'Système transparent',
    'ben-u3-desc': 'Toutes les opérations sont enregistrées. Vous savez toujours combien vous avez recyclé, gagné et dépensé.',
    'ben-b1-title': 'Nouveaux clients',
    'ben-b1-desc': "Accédez à une audience d'utilisateurs soucieux de l'environnement prêts à acheter.",
    'ben-b2-title': 'Image ESG',
    'ben-b2-desc': "Renforcez votre réputation d'entreprise socialement responsable et respectez les normes de développement durable.",
    'ben-b3-title': 'Marketing efficace',
    'ben-b3-desc': "Attirez des clients moins cher qu'avec la publicité traditionnelle, avec une conversion élevée.",
    'par-badge': 'Pour les entreprises',
    'par-h1': 'Devenez',
    'par-h2': 'partenaire',
    'par-desc': "Attirez des clients éco-responsables déjà motivés à acheter. Notre plateforme connecte votre entreprise avec une audience qui valorise le développement durable.",
    'par-feat1': "Accès à une base d'utilisateurs actifs",
    'par-feat2': 'Conditions de partenariat flexibles',
    'par-feat3': 'Analytique et rapports',
    'par-btn': 'Devenir partenaire',
    'par-cat-1': 'Cafés et restaurants',
    'par-cat-2': 'Supermarchés',
    'par-cat-3': 'Clubs de fitness',
    'par-cat-4': 'Boutiques en ligne',
    'par-cat-5': 'Cinémas',
    'par-cat-6': 'Pharmacies',
    'faq-badge': 'Support',
    'faq-title': 'Questions fréquentes',
    'faq-desc': 'Réponses aux questions populaires sur la plateforme',
    'faq-q1': 'Comment les points sont-ils crédités ?',
    'faq-a1': "Les points sont crédités selon le type et le poids des déchets déposés. Par exemple, vous obtenez plus de points par kilogramme de plastique que de papier. Tous les tarifs sont transparents et affichés dans l'app.",
    'faq-q2': 'Où puis-je déposer des déchets ?',
    'faq-a2': "Vous pouvez trouver le point de dépôt le plus proche sur la carte de l'app. Nous développons constamment notre réseau de points de collecte partenaires pour rendre le recyclage aussi pratique que possible.",
    'faq-q3': 'Sur quoi puis-je dépenser mes points ?',
    'faq-a3': 'Les points peuvent être échangés contre des réductions dans des magasins, cafés, clubs de fitness et autres organisations partenaires. La liste complète des offres est disponible dans la section Bonus de votre compte.',
    'faq-q4': 'Comment le système est-il protégé contre la fraude ?',
    'faq-a4': "Nous utilisons des codes QR, la géolocalisation et la pesée automatique pour vérifier les dépôts. Des limites s'appliquent au nombre d'opérations et un historique complet des actions est conservé.",
    'faq-q5': "L'inscription est-elle gratuite ?",
    'faq-a5': "Oui, l'inscription et l'utilisation de la plateforme sont entièrement gratuites pour les utilisateurs. Vous ne payez rien — vous gagnez seulement des points pour recycler vos déchets.",
    'faq-q6': 'Comment devenir partenaire de la plateforme ?',
    'faq-a6': "Pour les entreprises, nous proposons plusieurs modèles de collaboration. Soumettez une demande via le formulaire du site, et notre responsable vous contactera pour discuter des conditions.",
    'cta-badge': "Rejoignez-nous aujourd'hui",
    'cta-title': 'Commencez à gagner des points pour recycler',
    'cta-desc': "Rejoignez des milliers d'utilisateurs qui transforment déjà le soin de l'environnement en valeur réelle. L'inscription est gratuite et prend moins d'une minute.",
    'cta-btn1': 'Créer un compte',
    'cta-btn2': 'Nous contacter',
    'footer-desc': 'La plateforme qui rend le recyclage des déchets rentable pour tous.',
    'footer-col-platform': 'Plateforme',
    'footer-col-account': 'Compte',
    'footer-col-support': 'Support',
    'footer-link-hiw': 'Comment ça marche',
    'footer-link-dashboard': 'Tableau de bord',
    'footer-link-partners': 'Partenaires',
    'footer-link-bonuses': 'Bonus',
    'footer-link-login': 'Connexion',
    'footer-link-signup': "S'inscrire",
    'footer-link-qr': 'Code QR',
    'footer-link-contact': 'Contact',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'Nous écrire',
    'footer-coming-soon': 'Bientôt',
    'footer-social-soon': 'Réseaux sociaux — bientôt',
    'footer-copyright': '© 2026 EcoPoints. Tous droits réservés.',
    'my-rewards': 'Mes récompenses',
    'catalog': 'Catalogue',
    'no-redeemed': 'Vous n\'avez pas encore échangé de récompenses',
    'will-deduct': 'Points à déduire :',
    'confirm-btn': 'Confirmer',
    'cancel': 'Annuler',
    'redeemed-on': 'Obtenu le',
    'spent': 'pts dépensés',
  },
  de: {
    'how-it-works': 'So funktioniert es',
    benefits: 'Vorteile',
    partners: 'Partner',
    faq: 'Häufig gestellte Fragen',
    dashboard: 'Dashboard',
    login: 'Anmelden',
    signup: 'Registrieren',
    logout: 'Abmelden',
    theme: 'Design',
    language: 'Sprache',
    light: 'Hell',
    dark: 'Dunkel',
    system: 'System',
    start: 'Loslegen',
    open_menu: 'Menü öffnen',
    close_menu: 'Menü schließen',
    back: 'Dashboard',
    'qr-and-points': 'QR & Punkte',
    welcome: 'Willkommen!',
    'track-progress': 'Verfolgen Sie Ihren Fortschritt und erhalten Sie Prämien',
    'recent-activity': 'Letzte Aktivitäten',
    'available-rewards': 'Verfügbare Prämien',
    'all-rewards': 'Alle Prämien',
    'find-dropoff': 'Abgabepunkt finden',
    'dropoff-count': 'Über 500 Standorte in Ihrer Stadt',
    'open-map': 'Karte öffnen',
    'rewards-catalog': 'Prämien-Katalog',
    'your-balance': 'Ihr Guthaben',
    'get-reward': 'Einlösen',
    'not-enough-points': 'Nicht genug',
    'points-needed': 'Punkte fehlen',
    'redeem-soon': 'Einlösung bald verfügbar',
    'open-cabinet': 'Dashboard öffnen →',
    'qr-and-balance': 'QR-Code & Guthaben →',
    'your-ecopoints-card': 'Ihre EcoPoints-Karte',
    'show-code': 'Zeigen Sie den Code am Abgabepunkt oder teilen Sie eine Einladung',
    balance: 'Guthaben',
    'points-available': 'Punkte verfügbar',
    'member-card': 'Mitgliedskarte',
    'member-card-desc': 'Scannen Sie am Abgabepunkt zur Identifikation Ihres EcoPoints-Kontos.',
    'invite-friend': 'Freund einladen',
    'invite-friend-desc': 'Ein Freund folgt dem Link und registriert sich — Boni werden gemäß den Programmregeln gutgeschrieben.',
    'invite-code': 'Einladungscode',
    'cat-all': 'Alle',
    'cat-grocery': 'Lebensmittel',
    'cat-cafe': 'Café',
    'cat-online': 'Online',
    'cat-sport': 'Sport',
    'cat-transport': 'Transport',
    'points-label': 'Punkte',
    'kg-recycled': 'Recycelte kg',
    'rewards-count': 'Prämien',
    'act-plastic': '5 kg Plastik recycelt',
    'act-discount-cafe': '15% Rabatt bei Kofemainia',
    'act-paper': '3 kg Papier recycelt',
    'act-bonus': 'Aktivitätsbonus',
    'time-2h': 'Vor 2 Stunden',
    'time-yesterday': 'Gestern',
    'time-3d': 'Vor 3 Tagen',
    'time-week': 'Vor einer Woche',
    'points-word': 'Pkt.',
    'reward-perekrestok': '10% Rabatt bei Perekrestok',
    'reward-perekrestok-desc': 'Einkauf ab 500 ₽',
    'reward-starbucks': 'Gratis Kaffee bei Starbucks',
    'reward-starbucks-desc': 'Getränk bis 500 ml',
    'reward-ozon': '20% Rabatt bei Ozon',
    'reward-ozon-desc': 'Bestellung ab 1000 ₽',
    'reward-kofemainia': '15% Rabatt bei Kofemainia',
    'reward-kofemainia-desc': 'Gesamte Karte außer Alkohol',
    'reward-worldclass': '1-Tages-Pass bei World Class',
    'reward-worldclass-desc': 'Zugang zu allen Bereichen',
    'reward-vkusvill': '10% Rabatt bei VkusVill',
    'reward-vkusvill-desc': 'Gesamtes Sortiment',
    'reward-yandex': 'Yandex Go Fahrt',
    'reward-yandex-desc': 'Promo-Code über 150 ₽',
    'reward-lamoda': '25% Rabatt bei Lamoda',
    'reward-lamoda-desc': 'Erste Bestellung',
    'reward-fitnesshouse': 'Gratis Training bei Fitness House',
    'reward-fitnesshouse-desc': 'Einmaliger Besuch',
    'reward-magnit': '10% Rabatt bei Magnit',
    'reward-magnit-desc': 'Einkauf ab 300 ₽',
    'reward-costa': 'Gratis Kaffee bei Costa Coffee',
    'reward-costa-desc': 'Getränk Größe M',
    'reward-scooter': 'Scooter — 30 Min. gratis',
    'reward-scooter-desc': 'Fahrt-Promo-Code',
    'map-title': 'Karte der Abgabepunkte',
    'map-all-types': 'Alle',
    'map-use-location': 'Mein Standort',
    'map-locating': 'Orten...',
    'map-location-error': 'Standort nicht verfügbar',
    'map-points-found': 'Punkte gefunden',
    'map-nearest': 'Nächster',
    'map-km': 'km',
    'map-hours': 'Öffnungszeiten',
    'map-pts-per-kg': 'Pkt./kg',
    'map-route': 'Route',
    'map-you-are-here': 'Sie sind hier',
    'waste-plastic': 'Kunststoff',
    'waste-paper': 'Papier',
    'waste-glass': 'Glas',
    'waste-metal': 'Metall',
    'waste-electronics': 'Elektronik',
    'waste-organic': 'Organisch',
    'hero-badge': 'Ökologie + Vorteile = EcoPoints',
    'hero-h1-1': 'Wir machen aus Abfall',
    'hero-h1-2': 'echten Mehrwert',
    'hero-desc': 'Geben Sie Ihren Abfall zum Recycling ab, sammeln Sie Punkte und erhalten Sie echte Rabatte von unseren Partnern. Umweltschutz lohnt sich jetzt.',
    'hero-btn-primary': 'Punkte sammeln starten',
    'hero-btn-secondary': 'Mehr erfahren',
    'hero-stat-dropoff': 'Abgabepunkte',
    'hero-stat-partners': 'Partner',
    'hero-stat-users': 'Nutzer',
    'hiw-badge': 'Einfacher Prozess',
    'hiw-title': 'So funktioniert es',
    'hiw-desc': 'Von der Registrierung bis zu echten Boni — nur 4 einfache Schritte',
    'hiw-step1-title': 'Registrierung',
    'hiw-step1-desc': 'Erstellen Sie in wenigen Minuten ein Konto. Es ist kostenlos und dauert minimal.',
    'hiw-step2-title': 'Abfall abgeben',
    'hiw-step2-desc': 'Finden Sie den nächsten Abgabepunkt, scannen Sie den QR-Code und geben Sie Ihren sortierten Abfall ab.',
    'hiw-step3-title': 'Punkte erhalten',
    'hiw-step3-desc': 'Das System schreibt automatisch Punkte gut, abhängig von Art und Gewicht des abgegebenen Abfalls.',
    'hiw-step4-title': 'Gegen Boni einlösen',
    'hiw-step4-desc': 'Nutzen Sie gesammelte Punkte, um Rabatte und Angebote von unseren Partnern zu erhalten.',
    'ben-badge': 'Mehrwert für alle',
    'ben-title': 'Plattform-Vorteile',
    'ben-desc': 'EcoPoints schafft Mehrwert für Nutzer, Unternehmen und die Umwelt',
    'ben-for-users': 'Für Nutzer',
    'ben-for-biz': 'Für Unternehmen',
    'ben-u1-title': 'Echter Mehrwert',
    'ben-u1-desc': 'Erhalten Sie Rabatte und Boni von Hunderten von Partnern für eine einfache Aktion — Ihren Abfall recyceln.',
    'ben-u2-title': 'Persönlicher Fortschritt',
    'ben-u2-desc': 'Verfolgen Sie Ihren Umweltbeitrag: Gewicht des recycelten Abfalls, verdiente Punkte und gesparte Ressourcen.',
    'ben-u3-title': 'Transparentes System',
    'ben-u3-desc': 'Alle Vorgänge werden aufgezeichnet. Sie wissen immer, wie viel Sie recycelt, verdient und ausgegeben haben.',
    'ben-b1-title': 'Neue Kunden',
    'ben-b1-desc': 'Erhalten Sie Zugang zu einer Zielgruppe umweltbewusster Nutzer, die kaufbereit sind.',
    'ben-b2-title': 'ESG-Image',
    'ben-b2-desc': 'Stärken Sie Ihren Ruf als sozial verantwortliches Unternehmen und erfüllen Sie die Standards für nachhaltige Entwicklung.',
    'ben-b3-title': 'Effektives Marketing',
    'ben-b3-desc': 'Gewinnen Sie Kunden günstiger als durch traditionelle Werbung, mit hoher Conversion.',
    'par-badge': 'Für Unternehmen',
    'par-h1': 'Werden Sie',
    'par-h2': 'Partner',
    'par-desc': 'Gewinnen Sie umweltbewusste Kunden, die bereits kaufmotiviert sind. Unsere Plattform verbindet Ihr Unternehmen mit einer Zielgruppe, die nachhaltige Entwicklung schätzt.',
    'par-feat1': 'Zugang zur aktiven Nutzerbasis',
    'par-feat2': 'Flexible Partnerschaftsbedingungen',
    'par-feat3': 'Analysen und Berichte',
    'par-btn': 'Partner werden',
    'par-cat-1': 'Cafés & Restaurants',
    'par-cat-2': 'Supermärkte',
    'par-cat-3': 'Fitnessstudios',
    'par-cat-4': 'Online-Shops',
    'par-cat-5': 'Kinos',
    'par-cat-6': 'Apotheken',
    'faq-badge': 'Support',
    'faq-title': 'Häufig gestellte Fragen',
    'faq-desc': 'Antworten auf häufige Fragen zur Plattform',
    'faq-q1': 'Wie werden Punkte gutgeschrieben?',
    'faq-a1': 'Punkte werden je nach Art und Gewicht des abgegebenen Abfalls gutgeschrieben. Zum Beispiel erhalten Sie pro Kilogramm Kunststoff mehr Punkte als für Papier. Alle Tarife sind transparent und in der App einsehbar.',
    'faq-q2': 'Wo kann ich Abfall abgeben?',
    'faq-a2': 'Den nächsten Abgabepunkt finden Sie auf der Karte in der App. Wir erweitern ständig unser Netzwerk von Partnersammelstellen, um das Recycling so bequem wie möglich zu gestalten.',
    'faq-q3': 'Wofür kann ich Punkte ausgeben?',
    'faq-a3': 'Punkte können gegen Rabatte in Geschäften, Cafés, Fitnessstudios und anderen Partnerorganisationen eingetauscht werden. Die vollständige Liste der Angebote ist im Bereich Boni Ihres Kontos verfügbar.',
    'faq-q4': 'Wie ist das System vor Betrug geschützt?',
    'faq-a4': 'Wir verwenden QR-Codes, Geolokalisierung und automatisches Wiegen zur Verifizierung der Abgaben. Außerdem gelten Limits für die Anzahl der Vorgänge und es wird eine vollständige Aktivitätshistorie geführt.',
    'faq-q5': 'Ist die Registrierung kostenlos?',
    'faq-a5': 'Ja, die Registrierung und Nutzung der Plattform sind für Nutzer völlig kostenlos. Sie zahlen nichts — Sie verdienen nur Punkte fürs Recyclen.',
    'faq-q6': 'Wie werde ich Plattformpartner?',
    'faq-a6': 'Für Unternehmen bieten wir mehrere Kooperationsmodelle an. Reichen Sie eine Anfrage über das Formular auf der Website ein, und unser Manager wird sich mit Ihnen in Verbindung setzen.',
    'cta-badge': 'Jetzt mitmachen',
    'cta-title': 'Punkte fürs Recyceln sammeln starten',
    'cta-desc': 'Schließen Sie sich Tausenden von Nutzern an, die Umweltschutz bereits in echten Mehrwert verwandeln. Die Registrierung ist kostenlos und dauert weniger als eine Minute.',
    'cta-btn1': 'Konto erstellen',
    'cta-btn2': 'Kontakt aufnehmen',
    'footer-desc': 'Die Plattform, die Abfallrecycling für alle rentabel macht.',
    'footer-col-platform': 'Plattform',
    'footer-col-account': 'Konto',
    'footer-col-support': 'Support',
    'footer-link-hiw': 'So funktioniert es',
    'footer-link-dashboard': 'Dashboard',
    'footer-link-partners': 'Partner',
    'footer-link-bonuses': 'Boni',
    'footer-link-login': 'Anmelden',
    'footer-link-signup': 'Registrieren',
    'footer-link-qr': 'QR-Code',
    'footer-link-contact': 'Kontakt',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'E-Mail senden',
    'footer-coming-soon': 'Demnächst',
    'footer-social-soon': 'Social Media — demnächst',
    'footer-copyright': '© 2026 EcoPoints. Alle Rechte vorbehalten.',
    'my-rewards': 'Meine Prämien',
    'catalog': 'Katalog',
    'no-redeemed': 'Sie haben noch keine Prämien eingelöst',
    'will-deduct': 'Abzugspunkte:',
    'confirm-btn': 'Bestätigen',
    'cancel': 'Abbrechen',
    'redeemed-on': 'Eingelöst am',
    'spent': 'Pkt. ausgegeben',
  },
  ja: {
    'how-it-works': '使い方',
    benefits: 'メリット',
    partners: 'パートナー',
    faq: 'よくある質問',
    dashboard: 'ダッシュボード',
    login: 'ログイン',
    signup: '登録',
    logout: 'ログアウト',
    theme: 'テーマ',
    language: '言語',
    light: 'ライト',
    dark: 'ダーク',
    system: 'システム',
    start: '開始する',
    open_menu: 'メニューを開く',
    close_menu: 'メニューを閉じる',
    back: 'ダッシュボード',
    'qr-and-points': 'QR・ポイント',
    welcome: 'ようこそ！',
    'track-progress': '進捗を追跡して報酬を獲得しましょう',
    'recent-activity': '最近のアクティビティ',
    'available-rewards': '利用可能な報酬',
    'all-rewards': 'すべての報酬',
    'find-dropoff': '回収ポイントを探す',
    'dropoff-count': 'お近くに500か所以上',
    'open-map': '地図を開く',
    'rewards-catalog': '報酬カタログ',
    'your-balance': '残高',
    'get-reward': '獲得する',
    'not-enough-points': 'ポイント不足',
    'points-needed': 'ポイント不足',
    'redeem-soon': '交換機能は近日公開',
    'open-cabinet': 'ダッシュボードを開く →',
    'qr-and-balance': 'QRコード・残高 →',
    'your-ecopoints-card': 'EcoPointsカード',
    'show-code': '回収ポイントでコードを提示するか、招待状を共有してください',
    balance: '残高',
    'points-available': 'ポイント利用可能',
    'member-card': 'メンバーカード',
    'member-card-desc': '回収ポイントでスキャンしてEcoPointsアカウントを確認します。',
    'invite-friend': '友達を招待',
    'invite-friend-desc': '友達がリンクから登録すると、プログラムのルールに従ってボーナスが付与されます。',
    'invite-code': '招待コード',
    'cat-all': 'すべて',
    'cat-grocery': '食料品',
    'cat-cafe': 'カフェ',
    'cat-online': 'オンライン',
    'cat-sport': 'スポーツ',
    'cat-transport': '交通',
    'points-label': 'ポイント',
    'kg-recycled': 'リサイクルkg',
    'rewards-count': '報酬',
    'act-plastic': 'プラスチック5kgをリサイクル',
    'act-discount-cafe': 'Kofemainia 15%割引',
    'act-paper': '紙3kgをリサイクル',
    'act-bonus': 'アクティビティボーナス',
    'time-2h': '2時間前',
    'time-yesterday': '昨日',
    'time-3d': '3日前',
    'time-week': '1週間前',
    'points-word': 'pt',
    'reward-perekrestok': 'Perekrestok 10%割引',
    'reward-perekrestok-desc': '500 ₽以上のお買い物',
    'reward-starbucks': 'Starbucks 無料コーヒー',
    'reward-starbucks-desc': '500ml以下のドリンク',
    'reward-ozon': 'Ozon 20%割引',
    'reward-ozon-desc': '1000 ₽以上の注文',
    'reward-kofemainia': 'Kofemainia 15%割引',
    'reward-kofemainia-desc': 'アルコール以外の全メニュー',
    'reward-worldclass': 'World Class 1日パス',
    'reward-worldclass-desc': '全エリア利用可能',
    'reward-vkusvill': 'VkusVill 10%割引',
    'reward-vkusvill-desc': '全商品対象',
    'reward-yandex': 'Yandex Goライド',
    'reward-yandex-desc': '150 ₽プロモコード',
    'reward-lamoda': 'Lamoda 25%割引',
    'reward-lamoda-desc': '初回注文',
    'reward-fitnesshouse': 'Fitness House 無料トレーニング',
    'reward-fitnesshouse-desc': '1回利用',
    'reward-magnit': 'Magnit 10%割引',
    'reward-magnit-desc': '300 ₽以上のお買い物',
    'reward-costa': 'Costa Coffee 無料コーヒー',
    'reward-costa-desc': 'Mサイズドリンク',
    'reward-scooter': '電動キックボード30分無料',
    'reward-scooter-desc': 'ライドプロモコード',
    'map-title': '回収ポイント地図',
    'map-all-types': 'すべて',
    'map-use-location': '現在地',
    'map-locating': '位置確認中...',
    'map-location-error': '位置情報利用不可',
    'map-points-found': '地点が見つかりました',
    'map-nearest': '最寄り',
    'map-km': 'km',
    'map-hours': '営業時間',
    'map-pts-per-kg': 'pt/kg',
    'map-route': 'ルート',
    'map-you-are-here': '現在地',
    'waste-plastic': 'プラスチック',
    'waste-paper': '紙',
    'waste-glass': 'ガラス',
    'waste-metal': '金属',
    'waste-electronics': '電子機器',
    'waste-organic': '有機物',
    'hero-badge': 'エコロジー + お得 = EcoPoints',
    'hero-h1-1': 'ゴミを',
    'hero-h1-2': '価値に変える',
    'hero-desc': 'ゴミをリサイクルに出してポイントを貯め、パートナーから本物の割引を受けましょう。環境への配慮が今や得になります。',
    'hero-btn-primary': 'ポイントを貯め始める',
    'hero-btn-secondary': '詳しく見る',
    'hero-stat-dropoff': '回収ポイント',
    'hero-stat-partners': 'パートナー',
    'hero-stat-users': 'ユーザー',
    'hiw-badge': 'シンプルなプロセス',
    'hiw-title': '使い方',
    'hiw-desc': '登録から実際のボーナスまで — たった4ステップ',
    'hiw-step1-title': '登録',
    'hiw-step1-desc': '数分でアカウントを作成できます。無料で最小限の時間しかかかりません。',
    'hiw-step2-title': 'ゴミを出す',
    'hiw-step2-desc': '最寄りの回収ポイントを見つけ、QRコードをスキャンして分別したゴミを提出してください。',
    'hiw-step3-title': 'ポイントを獲得',
    'hiw-step3-desc': 'システムが提出されたゴミの種類と重さに応じて自動的にポイントを付与します。',
    'hiw-step4-title': 'ボーナスに交換',
    'hiw-step4-desc': '貯めたポイントを使ってパートナーからの割引や特典を受けましょう。',
    'ben-badge': 'みんなへの価値',
    'ben-title': 'プラットフォームの利点',
    'ben-desc': 'EcoPointsはユーザー、企業、環境に価値を生み出します',
    'ben-for-users': 'ユーザー向け',
    'ben-for-biz': '企業向け',
    'ben-u1-title': '本物の特典',
    'ben-u1-desc': 'シンプルな行動（ゴミのリサイクル）で数百のパートナーから割引とボーナスを受け取りましょう。',
    'ben-u2-title': '個人の進歩',
    'ben-u2-desc': '環境への貢献度を追跡しましょう：リサイクルされたゴミの重さ、獲得したポイント、節約した資源。',
    'ben-u3-title': '透明なシステム',
    'ben-u3-desc': 'すべての取引が記録されます。いつでもリサイクル量、獲得量、使用量を確認できます。',
    'ben-b1-title': '新しい顧客',
    'ben-b1-desc': '購買意欲のある環境意識の高いユーザー層にアクセスしましょう。',
    'ben-b2-title': 'ESGイメージ',
    'ben-b2-desc': '社会的責任企業としての評判を強化し、持続可能な開発基準を満たしましょう。',
    'ben-b3-title': '効果的なマーケティング',
    'ben-b3-desc': '高い転換率で従来の広告よりも安く顧客を獲得しましょう。',
    'par-badge': '企業向け',
    'par-h1': 'パートナーに',
    'par-h2': 'なりましょう',
    'par-desc': 'すでに購買意欲のある環境意識の高い顧客を引き付けましょう。私たちのプラットフォームはあなたのビジネスを持続可能な発展を重視するユーザーと結びつけます。',
    'par-feat1': 'アクティブユーザーベースへのアクセス',
    'par-feat2': '柔軟なパートナーシップ条件',
    'par-feat3': 'アナリティクスとレポート',
    'par-btn': 'パートナーになる',
    'par-cat-1': 'カフェ＆レストラン',
    'par-cat-2': 'スーパーマーケット',
    'par-cat-3': 'フィットネスクラブ',
    'par-cat-4': 'オンラインショップ',
    'par-cat-5': '映画館',
    'par-cat-6': '薬局',
    'faq-badge': 'サポート',
    'faq-title': 'よくある質問',
    'faq-desc': 'プラットフォームに関するよくある質問への回答',
    'faq-q1': 'ポイントはどのように付与されますか？',
    'faq-a1': 'ポイントは提出されたゴミの種類と重さに応じて付与されます。例えば、プラスチック1kgは紙よりも多くのポイントが付与されます。すべての料金は透明でアプリで確認できます。',
    'faq-q2': 'ゴミはどこに出せますか？',
    'faq-a2': 'アプリのマップで最寄りの回収ポイントを見つけることができます。リサイクルをできるだけ便利にするために、パートナー回収ポイントのネットワークを常に拡大しています。',
    'faq-q3': 'ポイントで何が買えますか？',
    'faq-a3': 'ポイントは店舗、カフェ、フィットネスクラブ、その他のパートナー機関での割引に交換できます。特典の全リストはアカウントのボーナスセクションで確認できます。',
    'faq-q4': '不正からシステムはどのように保護されていますか？',
    'faq-a4': 'QRコード、位置情報、自動計量を使用して提出を確認します。また、操作数に制限があり、完全な活動履歴が保持されます。',
    'faq-q5': '登録は無料ですか？',
    'faq-a5': 'はい、プラットフォームへの登録と利用はユーザーに完全に無料です。何も支払わず、ゴミのリサイクルでポイントを獲得するだけです。',
    'faq-q6': 'プラットフォームのパートナーになるにはどうすればよいですか？',
    'faq-a6': '企業向けにいくつかの協力モデルを提供しています。サイトのフォームから申請を提出していただければ、担当者が条件の話し合いのためにご連絡します。',
    'cta-badge': '今日参加しましょう',
    'cta-title': 'リサイクルでポイントを貯め始めよう',
    'cta-desc': '環境への配慮を本物の価値に変えている何千人ものユーザーに参加しましょう。登録は無料で1分もかかりません。',
    'cta-btn1': 'アカウント作成',
    'cta-btn2': 'お問い合わせ',
    'footer-desc': '廃棄物のリサイクルをみんなにとって有益にするプラットフォーム。',
    'footer-col-platform': 'プラットフォーム',
    'footer-col-account': 'アカウント',
    'footer-col-support': 'サポート',
    'footer-link-hiw': '使い方',
    'footer-link-dashboard': 'ダッシュボード',
    'footer-link-partners': 'パートナー',
    'footer-link-bonuses': 'ボーナス',
    'footer-link-login': 'ログイン',
    'footer-link-signup': '登録',
    'footer-link-qr': 'QRコード',
    'footer-link-contact': 'お問い合わせ',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'メール送信',
    'footer-coming-soon': '近日公開',
    'footer-social-soon': 'ソーシャルメディア — 近日公開',
    'footer-copyright': '© 2026 EcoPoints. 全著作権所有。',
    'my-rewards': 'マイ報酬',
    'catalog': 'カタログ',
    'no-redeemed': 'まだ報酬を交換していません',
    'will-deduct': '差し引かれるポイント：',
    'confirm-btn': '確認',
    'cancel': 'キャンセル',
    'redeemed-on': '交換日',
    'spent': 'pt使用',
  },
  ky: {
    'how-it-works': 'Кантип иштейт',
    benefits: 'Артыкчылыктар',
    partners: 'Өнөктөштөр',
    faq: 'Суроо-жооп',
    dashboard: 'Кабинет',
    login: 'Кирүү',
    signup: 'Катталуу',
    logout: 'Чыгуу',
    theme: 'Тема',
    language: 'Тил',
    light: 'Жарык',
    dark: 'Күңүрт',
    system: 'Система',
    start: 'Баштоо',
    open_menu: 'Менюну ачуу',
    close_menu: 'Менюну жабуу',
    back: 'Жеке кабинет',
    'qr-and-points': 'QR жана баллдар',
    welcome: 'Кош келиңиз!',
    'track-progress': 'Прогрессиңизди байкап, сыйлыктарды алыңыз',
    'recent-activity': 'Акыркы иш-аракеттер',
    'available-rewards': 'Жеткиликтүү сыйлыктар',
    'all-rewards': 'Бардык сыйлыктар',
    'find-dropoff': 'Кабыл алуу пунктун табуу',
    'dropoff-count': 'Шаарыңызда 500дөн ашык жер',
    'open-map': 'Картаны ачуу',
    'rewards-catalog': 'Сыйлыктар каталогу',
    'your-balance': 'Балансыңыз',
    'get-reward': 'Алуу',
    'not-enough-points': 'Баллдар жетишпейт',
    'points-needed': 'балл жетишпейт',
    'redeem-soon': 'Алмаштыруу жакында',
    'open-cabinet': 'Кабинетти ачуу →',
    'qr-and-balance': 'QR-код жана баланс →',
    'your-ecopoints-card': 'Сиздин EcoPoints картаңыз',
    'show-code': 'Кабыл алуу пунктунда кодду көрсөтүңүз же чакыруу жөнөтүңүз',
    balance: 'Баланс',
    'points-available': 'балл жеткиликтүү',
    'member-card': 'Катышуучунун картасы',
    'member-card-desc': 'EcoPoints аккаунтуңузду аныктоо үчүн кабыл алуу пунктунда сканерлеңиз.',
    'invite-friend': 'Досту чакыруу',
    'invite-friend-desc': 'Дос шилтеме аркылуу катталса — бонустар программанын эрежелерине ылайык эсептелет.',
    'invite-code': 'Чакыруу коду',
    'cat-all': 'Баары',
    'cat-grocery': 'Азык-түлүк',
    'cat-cafe': 'Кафе',
    'cat-online': 'Онлайн',
    'cat-sport': 'Спорт',
    'cat-transport': 'Транспорт',
    'points-label': 'Баллдар',
    'kg-recycled': 'Тапшырылган кг',
    'rewards-count': 'Сыйлыктар',
    'act-plastic': '5 кг пластик тапшырылды',
    'act-discount-cafe': 'Kofemainia дүкөнүндө 15% арзандатуу',
    'act-paper': '3 кг макулатура тапшырылды',
    'act-bonus': 'Активдүүлүк бонусу',
    'time-2h': '2 саат мурун',
    'time-yesterday': 'Кечээ',
    'time-3d': '3 күн мурун',
    'time-week': 'Бир жума мурун',
    'reward-perekrestok': 'Perekrestok дүкөнүндө 10% арзандатуу',
    'reward-starbucks': 'Starbucks кофеканасында акысыз кофе',
    'reward-ozon': 'Ozon дүкөнүндө 20% арзандатуу',
    'points-word': 'балл',
    'reward-perekrestok-desc': '500 ₽ дан жогору сатып алуу',
    'reward-starbucks-desc': '500 мл га чейин ичимдик',
    'reward-ozon-desc': '1000 ₽ дан жогору заказ',
    'reward-kofemainia': 'Kofemainia дүкөнүндө 15% арзандатуу',
    'reward-kofemainia-desc': 'Алкоголдон башка бардык меню',
    'reward-worldclass': 'World Class дарбазасында 1 күндүк абонемент',
    'reward-worldclass-desc': 'Клубдун бардык зоналарына кирүү',
    'reward-vkusvill': 'VkusVill дүкөнүндө 10% арзандатуу',
    'reward-vkusvill-desc': 'Бардык ассортиментке',
    'reward-yandex': 'Yandex Go жолго',
    'reward-yandex-desc': '150 ₽ промокод',
    'reward-lamoda': 'Lamoda дүкөнүндө 25% арзандатуу',
    'reward-lamoda-desc': 'Биринчи заказга',
    'reward-fitnesshouse': 'Fitness House спорт залында акысыз машыгуу',
    'reward-fitnesshouse-desc': 'Бир жолку баруу',
    'reward-magnit': 'Magnit дүкөнүндө 10% арзандатуу',
    'reward-magnit-desc': '300 ₽ дан жогору сатып алуу',
    'reward-costa': 'Costa Coffee кофеканасында акысыз кофе',
    'reward-costa-desc': 'M өлчөмдөгү ичимдик',
    'reward-scooter': 'Самокат — 30 мүнөт акысыз',
    'reward-scooter-desc': 'Жолго промокод',
    'map-title': 'Кабыл алуу пункттарынын картасы',
    'map-all-types': 'Баары',
    'map-use-location': 'Менин жайгашкан жерим',
    'map-locating': 'Аныкталууда...',
    'map-location-error': 'Жайгашкан жер жеткиликсиз',
    'map-points-found': 'пункт табылды',
    'map-nearest': 'Эң жакын',
    'map-km': 'км',
    'map-hours': 'Иш убактысы',
    'map-pts-per-kg': 'балл/кг',
    'map-route': 'Маршрут',
    'map-you-are-here': 'Сиз бул жердесиз',
    'waste-plastic': 'Пластик',
    'waste-paper': 'Кагаз',
    'waste-glass': 'Айнек',
    'waste-metal': 'Металл',
    'waste-electronics': 'Электроника',
    'waste-organic': 'Органика',
    'hero-badge': 'Экология + Пайда = EcoPoints',
    'hero-h1-1': 'Калдыктарды',
    'hero-h1-2': 'баалуулукка айландырабыз',
    'hero-desc': 'Калдыктарыңызды кайра иштетүүгө тапшырыңыз, баллдар топтоңуз жана өнөктөштөрдөн чыныгы арзандатуулар алыңыз. Экологияга кам көрүү эми пайдалуу.',
    'hero-btn-primary': 'Балл топтоону баштоо',
    'hero-btn-secondary': 'Көбүрөөк билүү',
    'hero-stat-dropoff': 'Кабыл алуу пункттары',
    'hero-stat-partners': 'Өнөктөштөр',
    'hero-stat-users': 'Колдонуучулар',
    'hiw-badge': 'Жөнөкөй процесс',
    'hiw-title': 'Кантип иштейт',
    'hiw-desc': 'Катталуудан чыныгы бонустарга чейин — жөн гана 4 жөнөкөй кадам',
    'hiw-step1-title': 'Катталуу',
    'hiw-step1-desc': 'Бир нече мүнөттө аккаунт түзүңүз. Акысыз жана аз убакыт алат.',
    'hiw-step2-title': 'Калдыктарды тапшыруу',
    'hiw-step2-desc': 'Эң жакын кабыл алуу пунктун табыңыз, QR-кодду сканерлеңиз жана сорттолгон калдыктарды тапшырыңыз.',
    'hiw-step3-title': 'Балл алуу',
    'hiw-step3-desc': 'Система тапшырылган калдыктардын түрүнө жана салмагына жараша автоматтык түрдө балл эсептейт.',
    'hiw-step4-title': 'Бонустарга алмаштыруу',
    'hiw-step4-desc': 'Топтолгон баллдарды өнөктөштөрдөн арзандатуулар жана сунуштар алуу үчүн пайдаланыңыз.',
    'ben-badge': 'Баарына пайда',
    'ben-title': 'Платформанын артыкчылыктары',
    'ben-desc': 'EcoPoints колдонуучулар, бизнес жана айлана-чөйрө үчүн баалуулук жаратат',
    'ben-for-users': 'Колдонуучулар үчүн',
    'ben-for-biz': 'Бизнес үчүн',
    'ben-u1-title': 'Чыныгы пайда',
    'ben-u1-desc': 'Жөнөкөй иш — калдыктарды кайра иштетүүгө тапшыруу — үчүн жүздөгөн өнөктөштөрдөн арзандатуулар жана бонустар алыңыз.',
    'ben-u2-title': 'Жеке прогресс',
    'ben-u2-desc': 'Экологияга салымыңызды байкаңыз: тапшырылган калдыктардын салмагы, таbылган баллдар жана үнөмдөлгөн ресурстар.',
    'ben-u3-title': 'Ачык-айкын система',
    'ben-u3-desc': 'Бардык операциялар жазылат. Сиз дайыма канча тапшырганыңызды, канча тапканыңызды жана кайда жумшаганыңызды билесиз.',
    'ben-b1-title': 'Жаңы кардарлар',
    'ben-b1-desc': 'Сатып алууга даяр экологиялык жактан аң-сезимдүү колдонуучулардын аудиториясына жетиңиз.',
    'ben-b2-title': 'ESG имиджи',
    'ben-b2-desc': 'Социалдык жоопкерчиликтүү компания катары беделиңизди бекемдеңиз жана туруктуу өнүгүү стандарттарына жооп бериңиз.',
    'ben-b3-title': 'Эффективдүү маркетинг',
    'ben-b3-desc': 'Жогорку конверсия менен салттуу жарнамадан арзаныраак кардарларды тартыңыз.',
    'par-badge': 'Бизнес үчүн',
    'par-h1': 'Өнөктөш',
    'par-h2': 'болуңуз',
    'par-desc': 'Сатып алуунун мотивациясы бар экологиялык жактан аң-сезимдүү кардарларды тартыңыз. Биздин платформа сиздин бизнесиңизди туруктуу өнүгүүнү баалаган аудитория менен байланыштырат.',
    'par-feat1': 'Активдүү колдонуучулар базасына кирүү',
    'par-feat2': 'Ийкемдүү өнөктөштүк шарттары',
    'par-feat3': 'Аналитика жана отчеттор',
    'par-btn': 'Өнөктөш болуу',
    'par-cat-1': 'Кафе жана ресторандар',
    'par-cat-2': 'Супермаркеттер',
    'par-cat-3': 'Фитнес-клубдар',
    'par-cat-4': 'Онлайн дүкөндөр',
    'par-cat-5': 'Кинотеатрлар',
    'par-cat-6': 'Аптекалар',
    'faq-badge': 'Колдоо',
    'faq-title': 'Көп берилүүчү суроолор',
    'faq-desc': 'Платформа боюнча популярдуу суроолорго жооптор',
    'faq-q1': 'Баллдар кантип эсептелет?',
    'faq-a1': 'Баллдар тапшырылган калдыктардын түрүнө жана салмагына жараша эсептелет. Мисалы, бир килограмм пластик кагаздан көбүрөөк балл берет. Бардык тарифтер ачык жана колдонмодо көрсөтүлгөн.',
    'faq-q2': 'Калдыктарды кайда тапшырса болот?',
    'faq-a2': 'Эң жакын кабыл алуу пунктун колдонмодогу картадан табууга болот. Кайра иштетүүнү мүмкүн болушунча ыңгайлуу кылуу үчүн биз өнөктөш кабыл алуу пункттарынын тармагын дайыма кеңейтебиз.',
    'faq-q3': 'Баллдарды эмнеге жумшаса болот?',
    'faq-a3': 'Баллдарды дүкөндөрдө, кафелерде, фитнес-клубдарда жана башка өнөктөш уюмдарда арзандатуулар алуу үчүн алмаштырса болот. Сунуштардын толук тизмеси жеке кабинетиңиздин «Бонустар» бөлүмүндө жеткиликтүү.',
    'faq-q4': 'Система алдамчылыктан кандай корголгон?',
    'faq-a4': 'Биз тапшырууну текшерүү үчүн QR-коддорду, геолокацияны жана автоматтык өлчөөнү колдонобуз. Ошондой эле операциялардын санына чек бар жана иш-аракеттердин толук тарыхы жүргүзүлөт.',
    'faq-q5': 'Катталуу акысызбы?',
    'faq-a5': 'Ооба, платформага катталуу жана аны колдонуу колдонуучулар үчүн толугу менен акысыз. Сиз эч нерсе төлөбөйсүз — калдыктарды тапшыруу үчүн балл гана топтойсуз.',
    'faq-q6': 'Платформанын өнөктөшү болуу үчүн эмне кылуу керек?',
    'faq-a6': 'Бизнес үчүн биз бир нече кызматташтык моделдерин сунуштайбыз. Сайттагы форма аркылуу арыз жөнөтүңүз, менеджерибиз шарттарды талкуулоо үчүн сиз менен байланышат.',
    'cta-badge': 'Бүгүн кошулуңуз',
    'cta-title': 'Кайра иштетүү үчүн балл топтоону баштаңыз',
    'cta-desc': 'Экологияга кам көрүүнү чыныгы баалуулукка айландырып жаткан миңдеген колдонуучуларга кошулуңуз. Катталуу акысыз жана бир мүнөттөн аз убакыт алат.',
    'cta-btn1': 'Аккаунт түзүү',
    'cta-btn2': 'Биз менен байланышуу',
    'footer-desc': 'Калдыктарды кайра иштетүүнү баарына пайдалуу кылган платформа.',
    'footer-col-platform': 'Платформа',
    'footer-col-account': 'Аккаунт',
    'footer-col-support': 'Колдоо',
    'footer-link-hiw': 'Кантип иштейт',
    'footer-link-dashboard': 'Жеке кабинет',
    'footer-link-partners': 'Өнөктөштөр',
    'footer-link-bonuses': 'Бонустар',
    'footer-link-login': 'Кирүү',
    'footer-link-signup': 'Катталуу',
    'footer-link-qr': 'QR-код',
    'footer-link-contact': 'Байланыш',
    'footer-link-faq': 'FAQ',
    'footer-link-write': 'Бизге жазуу',
    'footer-coming-soon': 'Жакында',
    'footer-social-soon': 'Социалдык тармактар — жакында',
    'footer-copyright': '© 2026 EcoPoints. Бардык укуктар корголгон.',
    'my-rewards': 'Менин сыйлыктарым',
    'catalog': 'Каталог',
    'no-redeemed': 'Сиз азырынча бирдей сыйлык алган жоксуз',
    'will-deduct': 'Спишилет:',
    'confirm-btn': 'Ырастоо',
    'cancel': 'Жокко чыгаруу',
    'redeemed-on': 'Алынды',
    'spent': 'балл',
  },
}

export const getTranslation = (lang: Language, key: string): string => {
  return translations[lang]?.[key] || translations.en[key] || key
}
